#############################################
FROM python:3.12-slim

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/ 

WORKDIR /app
ADD eida_consistency/automate_eida_consistency.py .
RUN uv sync --script automate_eida_consistency.py
ADD eida_nodes eida_nodes
CMD uv run automate_eida_consistency.py