#############################################
# Install uv
FROM python:3.12-slim

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

WORKDIR /app
ADD perf_checks/webscenarios_perfcheck.py .
RUN uv sync --script webscenarios_perfcheck.py
ADD eida_nodes eida_nodes
CMD uv run webscenarios_perfcheck.py