#############################################
FROM python:3.12-slim

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/ 

USER 1500
WORKDIR /app
ADD eida_consistency/eida_consistency_wrapper.py .
RUN uv sync --script eida_consistency_wrapper.py
ADD eida_nodes eida_nodes
CMD uv run eida_consistency_wrapper.py
