apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "oculus-zbx-agent.fullname" . }}
  labels:
    {{- include "oculus-zbx-agent.labels" . | nindent 4 }}
data:
  zbx_lld: |-
{{ .Values.zbx_lld | nindent 4 }}
  eida_userparameter.conf: |
    UserParameter=eida.lld,cat /etc/zabbix/zabbix_agentd.d/monitoring_lld.json
  hostinterface.conf: |
    # When a host is discovered, this parameter is used for DNS as default interface
    HostInterface={{ include "oculus-zbx-agent.fullname" . }}
  generate_lld.py: |-
    {{- $.Files.Get "scripts/generate_lld.py" | nindent 4 }}

