
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "oculus-zbx-agent.fullname" . }}
  labels:
    {{- include "oculus-zbx-agent.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "oculus-zbx-agent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        {{- include "oculus-zbx-agent.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "oculus-zbx-agent.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "oculus-zbx-agent.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: ZBX_SERVER_HOST
              value: "{{ .Values.zabbixServer.host }}, 0.0.0.0/0"
            - name: ZBX_SERVER_PORT
              value: "{{ .Values.zabbixServer.port }}"
            - name: ZBX_HOSTNAME
              value: {{ include "oculus-zbx-agent.fullname" . }}
            - name: ZBX_DEBUGLEVEL
              value: "4"
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: /etc/zabbix/zabbix_agentd.d/eida_userparameter.conf
              subPath: eida_userparameter.conf
            - name: config
              mountPath: /etc/zabbix/zabbix_agentd.d/monitoring_lld.json
              subPath: monitoring_lld.json
            - name: config
              mountPath: /etc/zabbix/zabbix_agentd.d/hostinterface.conf
              subPath: hostinterface.conf
            - name: config
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
