apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "oculus-zbx-agent.fullname" . }}
  labels:
    {{- include "oculus-zbx-agent.labels" . | nindent 4 }}
  annotation:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  tempalte:
    spec:
      initContainers:
        - name: {{- include "oculus-zbx-agent.fullname"}}-pre-upgrade
          image: python:3.12
          command: ['sh', '-c']
          args:
            - |
              python3 /scripts/generate_lld_print.py {{ .Values.inputYaml }} > /etc/zabbix/zabbix_agentd.d/monitoring_lld.json  
          volumeMounts:
            - name: config
              mountPath: /etc/zabbix/zabbix_agentd.d/monitoring_lld.json
              subPath: monitoring_lld.json
      restartPolicy: Never



init container

faire volume contenue file.yaml

passer le chemin volume et le lire par le script python

emptyDir (monter par les deux RW / ROnly > écrire résultat script 