apiVersion: v1
kind: Service
metadata:
  name: {{ include "oculus-zbx-agent.fullname" . }}
  labels: {{- include "oculus-zbx-agent.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector: {{- include "oculus-zbx-agent.selectorLabels" . | nindent 4 }}
