- macro: "{$NODE}"
  value: 'BGR'
- macro: "{$ENDPOINT}"
  value: 'eida.bgr.de'
- macro: "{$ROUTINGFILE}"
  value: 'eidaws/routing/routing.xml'
- macro: "{$ONLINECHECK_NET}"
  value: 'GR'
- macro: "{$ONLINECHECK_STA}"
  value: 'ASSE'
- macro: "{$ONLINECHECK_LOC}"
  value: '*'
- macro: "{$ONLINECHECK_CHA}"
  value: 'HHZ'
- macro: "{$ONLINECHECK_START}"
  value: '2017-07-01T00:01:00'
- macro: "{$ONLINECHECK_END}"
  value: '2017-07-01T00:01:10'
- macro: "{$PERFCHECK_DATASELECT_9STREAMS_NET}"
  value: 'GR'
- macro: "{$PERFCHECK_DATASELECT_9STREAMS_STA}"
  value: 'ASSE,BFO,MOX'
- macro: "{$PERFCHECK_DATASELECT_9STREAMS_LOC}"
  value: '*'
- macro: "{$PERFCHECK_DATASELECT_9STREAMS_CHA}"
  value: 'HH*'
- macro: "{$PERFCHECK_DATASELECT_9STREAMS_START}"
  value: '2017-07-01T00:01:00'
- macro: "{$PERFCHECK_DATASELECT_9STREAMS_END}"
  value: '2017-07-01T00:02:00'
- macro: "{$PERFCHECK_DATASELECT_54STREAMS_NET}"
  value: 'SX,TH,GR'
- macro: "{$PERFCHECK_DATASELECT_54STREAMS_STA}"
  value: '*'
- macro: "{$PERFCHECK_DATASELECT_54STREAMS_LOC}"
  value: '*'
- macro: "{$PERFCHECK_DATASELECT_54STREAMS_CHA}"
  value: 'HHZ'
- macro: "{$PERFCHECK_DATASELECT_54STREAMS_START}"
  value: '2011-01-03T00:01:00'
- macro: "{$PERFCHECK_DATASELECT_54STREAMS_END}"
  value: '2011-01-03T00:02:00'
- macro: "{$PERFCHECK_DATASELECT_320STREAMS_NET}"
  value: 'SX,TH,GR'
- macro: "{$PERFCHECK_DATASELECT_320STREAMS_STA}"
  value: '*'
- macro: "{$PERFCHECK_DATASELECT_320STREAMS_LOC}"
  value: '*'
- macro: "{$PERFCHECK_DATASELECT_320STREAMS_CHA}"
  value: 'HH*,EH*'
- macro: "{$PERFCHECK_DATASELECT_320STREAMS_START}"
  value: '2016-07-06T00:01:00'
- macro: "{$PERFCHECK_DATASELECT_320STREAMS_END}"
  value: '2016-07-06T00:02:00'
- macro: "{$PERFCHECK_DATASELECT_1STREAM15DAYS_NET}"
  value: 'GR'
- macro: "{$PERFCHECK_DATASELECT_1STREAM15DAYS_STA}"
  value: 'BFO'
- macro: "{$PERFCHECK_DATASELECT_1STREAM15DAYS_LOC}"
  value: '*'
- macro: "{$PERFCHECK_DATASELECT_1STREAM15DAYS_CHA}"
  value: 'HH?'
- macro: "{$PERFCHECK_DATASELECT_1STREAM15DAYS_START}"
  value: '2012-06-04T00:00:00'
- macro: "{$PERFCHECK_DATASELECT_1STREAM15DAYS_END}"
  value: '2012-06-19T00:00:00'
- macro: "{$PERFCHECK_WFCATALOG_9STREAMS_NET}"
  value: 'GR'
- macro: "{$PERFCHECK_WFCATALOG_9STREAMS_STA}"
  value: 'ASSE,BFO,MOX'
- macro: "{$PERFCHECK_WFCATALOG_9STREAMS_LOC}"
  value: '*'
- macro: "{$PERFCHECK_WFCATALOG_9STREAMS_CHA}"
  value: 'HH*'
- macro: "{$PERFCHECK_WFCATALOG_9STREAMS_START}"
  value: '2017-07-01T00:01:00'
- macro: "{$PERFCHECK_WFCATALOG_9STREAMS_END}"
  value: '2017-07-01T00:02:00'
- macro: "{$PERFCHECK_WFCATALOG_54STREAMS_NET}"
  value: 'SX,TH,GR'
- macro: "{$PERFCHECK_WFCATALOG_54STREAMS_STA}"
  value: '*'
- macro: "{$PERFCHECK_WFCATALOG_54STREAMS_LOC}"
  value: '*'
- macro: "{$PERFCHECK_WFCATALOG_54STREAMS_CHA}"
  value: 'HHZ'
- macro: "{$PERFCHECK_WFCATALOG_54STREAMS_START}"
  value: '2011-01-03T00:01:00'
- macro: "{$PERFCHECK_WFCATALOG_54STREAMS_END}"
  value: '2011-01-03T00:02:00'
- macro: "{$PERFCHECK_WFCATALOG_320STREAMS_NET}"
  value: 'SX,TH,GR'
- macro: "{$PERFCHECK_WFCATALOG_320STREAMS_STA}"
  value: '*'
- macro: "{$PERFCHECK_WFCATALOG_320STREAMS_LOC}"
  value: '*'
- macro: "{$PERFCHECK_WFCATALOG_320STREAMS_CHA}"
  value: 'HH*,EH*'
- macro: "{$PERFCHECK_WFCATALOG_320STREAMS_START}"
  value: '2016-07-06T00:01:00'
- macro: "{$PERFCHECK_WFCATALOG_320STREAMS_END}"
  value: '2016-07-06T00:02:00'
- macro: "{$PERFCHECK_WFCATALOG_1STREAM15DAYS_NET}"
  value: 'GR'
- macro: "{$PERFCHECK_WFCATALOG_1STREAM15DAYS_STA}"
  value: 'BFO'
- macro: "{$PERFCHECK_WFCATALOG_1STREAM15DAYS_LOC}"
  value: '--'
- macro: "{$PERFCHECK_WFCATALOG_1STREAM15DAYS_CHA}"
  value: 'HH?'
- macro: "{$PERFCHECK_WFCATALOG_1STREAM15DAYS_START}"
  value: '2012-06-04T00:00:00'
- macro: "{$PERFCHECK_WFCATALOG_1STREAM15DAYS_END}"
  value: '2012-06-19T00:00:00'
- macro: "{$PERFCHECK_AVAILABILITY_9STREAMS_NET}"
  value: 'GR'
- macro: "{$PERFCHECK_AVAILABILITY_9STREAMS_STA}"
  value: 'ASSE,BFO,MOX'
- macro: "{$PERFCHECK_AVAILABILITY_9STREAMS_LOC}"
  value: '*'
- macro: "{$PERFCHECK_AVAILABILITY_9STREAMS_CHA}"
  value: 'HH*'
- macro: "{$PERFCHECK_AVAILABILITY_9STREAMS_START}"
  value: '2017-07-01T00:01:00'
- macro: "{$PERFCHECK_AVAILABILITY_9STREAMS_END}"
  value: '2017-07-01T23:59:00'
- macro: "{$PERFCHECK_AVAILABILITY_54STREAMS_NET}"
  value: 'SX,TH,GR'
- macro: "{$PERFCHECK_AVAILABILITY_54STREAMS_STA}"
  value: '*'
- macro: "{$PERFCHECK_AVAILABILITY_54STREAMS_LOC}"
  value: '*'
- macro: "{$PERFCHECK_AVAILABILITY_54STREAMS_CHA}"
  value: 'HHZ'
- macro: "{$PERFCHECK_AVAILABILITY_54STREAMS_START}"
  value: '2011-01-03T00:01:00'
- macro: "{$PERFCHECK_AVAILABILITY_54STREAMS_END}"
  value: '2011-01-03T23:59:00'
- macro: "{$PERFCHECK_AVAILABILITY_320STREAMS_NET}"
  value: 'SX,TH,GR'
- macro: "{$PERFCHECK_AVAILABILITY_320STREAMS_STA}"
  value: '*'
- macro: "{$PERFCHECK_AVAILABILITY_320STREAMS_LOC}"
  value: '*'
- macro: "{$PERFCHECK_AVAILABILITY_320STREAMS_CHA}"
  value: 'HH*,EH*'
- macro: "{$PERFCHECK_AVAILABILITY_320STREAMS_START}"
  value: '2016-07-06T00:01:00'
- macro: "{$PERFCHECK_AVAILABILITY_320STREAMS_END}"
  value: '2016-07-06T23:59:00'
- macro: "{$PERFCHECK_AVAILABILITY_1STREAM15DAYS_NET}"
  value: 'GR'
- macro: "{$PERFCHECK_AVAILABILITY_1STREAM15DAYS_STA}"
  value: 'BFO'
- macro: "{$PERFCHECK_AVAILABILITY_1STREAM15DAYS_LOC}"
  value: '*'
- macro: "{$PERFCHECK_AVAILABILITY_1STREAM15DAYS_CHA}"
  value: 'HH?'
- macro: "{$PERFCHECK_AVAILABILITY_1STREAM15DAYS_START}"
  value: '2012-06-04T00:00:00'
- macro: "{$PERFCHECK_AVAILABILITY_1STREAM15DAYS_END}"
  value: '2012-06-19T00:00:00'
- macro: "{$PERFCHECK_STATION_9STREAMS_NET}"
  value: 'GR'
- macro: "{$PERFCHECK_STATION_9STREAMS_STA}"
  value: 'ASSE,BFO,MOX'
- macro: "{$PERFCHECK_STATION_9STREAMS_LOC}"
  value: '*'
- macro: "{$PERFCHECK_STATION_9STREAMS_CHA}"
  value: 'HH*'
- macro: "{$PERFCHECK_STATION_9STREAMS_START}"
  value: '2017-07-01T00:01:00'
- macro: "{$PERFCHECK_STATION_9STREAMS_END}"
  value: '2017-07-01T00:02:00'
- macro: "{$PERFCHECK_STATION_54STREAMS_NET}"
  value: 'GR,SX,TH'
- macro: "{$PERFCHECK_STATION_54STREAMS_STA}"
  value: '*'
- macro: "{$PERFCHECK_STATION_54STREAMS_LOC}"
  value: '*'
- macro: "{$PERFCHECK_STATION_54STREAMS_CHA}"
  value: 'HHZ'
- macro: "{$PERFCHECK_STATION_54STREAMS_START}"
  value: '2011-01-05T23:01:00'
- macro: "{$PERFCHECK_STATION_54STREAMS_END}"
  value: '2011-01-05T23:02:00'
- macro: "{$PERFCHECK_STATION_320STREAMS_NET}"
  value: 'GR,SX,TH'
- macro: "{$PERFCHECK_STATION_320STREAMS_STA}"
  value: '*'
- macro: "{$PERFCHECK_STATION_320STREAMS_LOC}"
  value: '*'
- macro: "{$PERFCHECK_STATION_320STREAMS_CHA}"
  value: 'HH*,EH*'
- macro: "{$PERFCHECK_STATION_320STREAMS_START}"
  value: '2016-07-06T23:01:00'
- macro: "{$PERFCHECK_STATION_320STREAMS_END}"
  value: '2016-07-06T23:02:00'
