- macro: "{$NODE}"
  value: 'ICGC'
- macro: "{$ENDPOINT}"
  value: 'ws.icgc.cat'
- macro: "{$ROUTINGFILE}"
  value: 'eidaws/routing/routing.xml'
- macro: "{$ONLINECHECK_NET}"
  value: 'CA'
- macro: "{$ONLINECHECK_STA}"
  value: 'VNIG'
- macro: "{$ONLINECHECK_LOC}"
  value: '--'
- macro: "{$ONLINECHECK_CHA}"
  value: 'HHZ'
- macro: "{$ONLINECHECK_START}"
  value: '2024-12-22T00:00:00'
- macro: "{$ONLINECHECK_END}"
  value: '2024-12-22T00:00:10'
- macro: "{$PERFCHECK_DATASELECT_9STREAMS_NET}"
  value: 'CA'
- macro: "{$PERFCHECK_DATASELECT_9STREAMS_STA}"
  value: 'CMAS,CORI,EBR'
- macro: "{$PERFCHECK_DATASELECT_9STREAMS_LOC}"
  value: '*'
- macro: "{$PERFCHECK_DATASELECT_9STREAMS_CHA}"
  value: 'HH?,HNE'
- macro: "{$PERFCHECK_DATASELECT_9STREAMS_START}"
  value: '2019-11-07T00:01:00'
- macro: "{$PERFCHECK_DATASELECT_9STREAMS_END}"
  value: '2019-11-07T00:02:00'
- macro: "{$PERFCHECK_DATASELECT_54STREAMS_NET}"
  value: 'CA'
- macro: "{$PERFCHECK_DATASELECT_54STREAMS_STA}"
  value: 'CAVN,CBEU,CBRU,CBUD,CEST,CGAR,CLLI,CORG,CPAL,CTRE,CARA,ARBS,FBR,POBL,BLAN,BAJU,CGIR,CGRN,SCOL,MTJR,OLOS,VIES'
- macro: "{$PERFCHECK_DATASELECT_54STREAMS_LOC}"
  value: '*'
- macro: "{$PERFCHECK_DATASELECT_54STREAMS_CHA}"
  value: 'HH?,HNE'
- macro: "{$PERFCHECK_DATASELECT_54STREAMS_START}"
  value: '2018-10-12T00:01:00'
- macro: "{$PERFCHECK_DATASELECT_54STREAMS_END}"
  value: '2018-10-12T00:02:00'
- macro: "{$PERFCHECK_DATASELECT_320STREAMS_NET}"
  value: '*'
- macro: "{$PERFCHECK_DATASELECT_320STREAMS_STA}"
  value: '*'
- macro: "{$PERFCHECK_DATASELECT_320STREAMS_LOC}"
  value: '*'
- macro: "{$PERFCHECK_DATASELECT_320STREAMS_CHA}"
  value: '*'
- macro: "{$PERFCHECK_DATASELECT_320STREAMS_START}"
  value: '2020-08-05T00:01:00'
- macro: "{$PERFCHECK_DATASELECT_320STREAMS_END}"
  value: '2020-08-05T00:02:00'
- macro: "{$PERFCHECK_DATASELECT_1STREAM15DAYS_NET}"
  value: 'CA'
- macro: "{$PERFCHECK_DATASELECT_1STREAM15DAYS_STA}"
  value: 'CBEU'
- macro: "{$PERFCHECK_DATASELECT_1STREAM15DAYS_LOC}"
  value: '*'
- macro: "{$PERFCHECK_DATASELECT_1STREAM15DAYS_CHA}"
  value: 'HH?'
- macro: "{$PERFCHECK_DATASELECT_1STREAM15DAYS_START}"
  value: '2012-06-08T00:00:00'
- macro: "{$PERFCHECK_DATASELECT_1STREAM15DAYS_END}"
  value: '2012-06-23T00:00:00'
- macro: "{$PERFCHECK_WFCATALOG_9STREAMS_NET}"
  value: 'CA'
- macro: "{$PERFCHECK_WFCATALOG_9STREAMS_STA}"
  value: 'CMAS,CORI,EBR'
- macro: "{$PERFCHECK_WFCATALOG_9STREAMS_LOC}"
  value: '*'
- macro: "{$PERFCHECK_WFCATALOG_9STREAMS_CHA}"
  value: 'HH?,HNE'
- macro: "{$PERFCHECK_WFCATALOG_9STREAMS_START}"
  value: '2019-11-07T00:01:00'
- macro: "{$PERFCHECK_WFCATALOG_9STREAMS_END}"
  value: '2019-11-07T00:02:00'
- macro: "{$PERFCHECK_WFCATALOG_54STREAMS_NET}"
  value: 'CA'
- macro: "{$PERFCHECK_WFCATALOG_54STREAMS_STA}"
  value: 'CAVN,CBEU,CBRU,CBUD,CEST,CGAR,CLLI,CORG,CPAL,CTRE,CARA,ARBS,FBR,POBL,BLAN,BAJU,CGIR,CGRN,SCOL,MTJR,OLOS,VIES'
- macro: "{$PERFCHECK_WFCATALOG_54STREAMS_LOC}"
  value: '*'
- macro: "{$PERFCHECK_WFCATALOG_54STREAMS_CHA}"
  value: 'HH?,HNE'
- macro: "{$PERFCHECK_WFCATALOG_54STREAMS_START}"
  value: '2018-10-12T00:01:00'
- macro: "{$PERFCHECK_WFCATALOG_54STREAMS_END}"
  value: '2018-10-12T00:02:00'
- macro: "{$PERFCHECK_WFCATALOG_320STREAMS_NET}"
  value: '*'
- macro: "{$PERFCHECK_WFCATALOG_320STREAMS_STA}"
  value: '*'
- macro: "{$PERFCHECK_WFCATALOG_320STREAMS_LOC}"
  value: '*'
- macro: "{$PERFCHECK_WFCATALOG_320STREAMS_CHA}"
  value: '*'
- macro: "{$PERFCHECK_WFCATALOG_320STREAMS_START}"
  value: '*'
- macro: "{$PERFCHECK_WFCATALOG_320STREAMS_END}"
  value: '*'
- macro: "{$PERFCHECK_WFCATALOG_1STREAM15DAYS_NET}"
  value: 'CA'
- macro: "{$PERFCHECK_WFCATALOG_1STREAM15DAYS_STA}"
  value: 'CBEU'
- macro: "{$PERFCHECK_WFCATALOG_1STREAM15DAYS_LOC}"
  value: '--'
- macro: "{$PERFCHECK_WFCATALOG_1STREAM15DAYS_CHA}"
  value: 'HH?'
- macro: "{$PERFCHECK_WFCATALOG_1STREAM15DAYS_START}"
  value: '2012-06-08T00:00:00'
- macro: "{$PERFCHECK_WFCATALOG_1STREAM15DAYS_END}"
  value: '2012-06-23T00:00:00'
- macro: "{$PERFCHECK_AVAILABILITY_9STREAMS_NET}"
  value: 'CA'
- macro: "{$PERFCHECK_AVAILABILITY_9STREAMS_STA}"
  value: 'CMAS,CORI,EBR'
- macro: "{$PERFCHECK_AVAILABILITY_9STREAMS_LOC}"
  value: '*'
- macro: "{$PERFCHECK_AVAILABILITY_9STREAMS_CHA}"
  value: 'HH?,HNE'
- macro: "{$PERFCHECK_AVAILABILITY_9STREAMS_START}"
  value: '2019-11-07T00:01:00'
- macro: "{$PERFCHECK_AVAILABILITY_9STREAMS_END}"
  value: '2019-11-07T23:59:00'
- macro: "{$PERFCHECK_AVAILABILITY_54STREAMS_NET}"
  value: 'CA'
- macro: "{$PERFCHECK_AVAILABILITY_54STREAMS_STA}"
  value: 'CAVN,CBEU,CBRU,CBUD,CEST,CGAR,CLLI,CORG,CPAL,CTRE,CARA,ARBS,FBR,POBL,BLAN,BAJU,CGIR,CGRN,SCOL,MTJR,OLOS,VIES'
- macro: "{$PERFCHECK_AVAILABILITY_54STREAMS_LOC}"
  value: '*'
- macro: "{$PERFCHECK_AVAILABILITY_54STREAMS_CHA}"
  value: 'HH?,HNE'
- macro: "{$PERFCHECK_AVAILABILITY_54STREAMS_START}"
  value: '2018-10-12T00:01:00'
- macro: "{$PERFCHECK_AVAILABILITY_54STREAMS_END}"
  value: '2018-10-12T23:59:00'
- macro: "{$PERFCHECK_AVAILABILITY_320STREAMS_NET}"
  value: '*'
- macro: "{$PERFCHECK_AVAILABILITY_320STREAMS_STA}"
  value: '*'
- macro: "{$PERFCHECK_AVAILABILITY_320STREAMS_LOC}"
  value: '*'
- macro: "{$PERFCHECK_AVAILABILITY_320STREAMS_CHA}"
  value: '*'
- macro: "{$PERFCHECK_AVAILABILITY_320STREAMS_START}"
  value: '2020-08-05T00:01:00'
- macro: "{$PERFCHECK_AVAILABILITY_320STREAMS_END}"
  value: '2020-08-05T23:59:00'
- macro: "{$PERFCHECK_AVAILABILITY_1STREAM15DAYS_NET}"
  value: 'CA'
- macro: "{$PERFCHECK_AVAILABILITY_1STREAM15DAYS_STA}"
  value: 'CBEU'
- macro: "{$PERFCHECK_AVAILABILITY_1STREAM15DAYS_LOC}"
  value: '*'
- macro: "{$PERFCHECK_AVAILABILITY_1STREAM15DAYS_CHA}"
  value: 'HH?'
- macro: "{$PERFCHECK_AVAILABILITY_1STREAM15DAYS_START}"
  value: '2012-06-08T00:00:00'
- macro: "{$PERFCHECK_AVAILABILITY_1STREAM15DAYS_END}"
  value: '2012-06-23T00:00:00'
- macro: "{$PERFCHECK_STATION_9STREAMS_NET}"
  value: '*'
- macro: "{$PERFCHECK_STATION_9STREAMS_STA}"
  value: '*'
- macro: "{$PERFCHECK_STATION_9STREAMS_LOC}"
  value: '*'
- macro: "{$PERFCHECK_STATION_9STREAMS_CHA}"
  value: '*'
- macro: "{$PERFCHECK_STATION_9STREAMS_START}"
  value: '*'
- macro: "{$PERFCHECK_STATION_9STREAMS_END}"
  value: '*'
- macro: "{$PERFCHECK_STATION_54STREAMS_NET}"
  value: 'CA'
- macro: "{$PERFCHECK_STATION_54STREAMS_STA}"
  value: 'CAVN,CBEU,CBRU,CBUD,CEST,CGAR,CLLI,CORG,CPAL,CTRE,CARA,ARBS,FBR,POBL,BLAN,BAJU,CGIR,CGRN,SCOL,MTJR,OLOS,VIES'
- macro: "{$PERFCHECK_STATION_54STREAMS_LOC}"
  value: '*'
- macro: "{$PERFCHECK_STATION_54STREAMS_CHA}"
  value: '*'
- macro: "{$PERFCHECK_STATION_54STREAMS_START}"
  value: '2018-09-15T00:01:00'
- macro: "{$PERFCHECK_STATION_54STREAMS_END}"
  value: '2018-09-15T00:02:00'
- macro: "{$PERFCHECK_STATION_320STREAMS_NET}"
  value: 'CA,YK,ES'
- macro: "{$PERFCHECK_STATION_320STREAMS_STA}"
  value: '*'
- macro: "{$PERFCHECK_STATION_320STREAMS_LOC}"
  value: '*'
- macro: "{$PERFCHECK_STATION_320STREAMS_CHA}"
  value: '*'
- macro: "{$PERFCHECK_STATION_320STREAMS_START}"
  value: '2011-12-22T00:00:00'
- macro: "{$PERFCHECK_STATION_320STREAMS_END}"
  value: '2019-05-20T00:10:00'
