- macro: "{$NODE}"
  value: 'IGN'
- macro: "{$ENDPOINT}"
  value: 'fdsnws.sismologia.ign.es'
- macro: "{$ROUTINGFILE}"
  value: ''
- macro: "{$ONLINECHECK_NET}"
  value: 'ES'
- macro: "{$ONLINECHECK_STA}"
  value: 'YEBES'
- macro: "{$ONLINECHECK_LOC}"
  value: '*'
- macro: "{$ONLINECHECK_CHA}"
  value: 'HHZ'
- macro: "{$ONLINECHECK_START}"
  value: '2025-06-25T23:00:00'
- macro: "{$ONLINECHECK_END}"
  value: '2025-06-25T23:00:10'
- macro: "{$CERT.WEBSITE.HOSTNAME}"
  value: 'fdsnws.sismologia.ign.es'
