- macro: "{$NODE}"
  value: 'KOERI'
- macro: "{$ENDPOINT}"
  value: 'eida.koeri.boun.edu.tr'
- macro: "{$ROUTINGFILE}"
  value: 'routing/routing.xml'
- macro: "{$ONLINECHECK_NET}"
  value: 'KO'
- macro: "{$ONLINECHECK_STA}"
  value: 'KMAH'
- macro: "{$ONLINECHECK_LOC}"
  value: '--'
- macro: "{$ONLINECHECK_CHA}"
  value: 'HHZ'
- macro: "{$ONLINECHECK_START}"
  value: '2025-04-01T00:00:00'
- macro: "{$ONLINECHECK_END}"
  value: '2025-04-01T00:00:05'
- macro: "{$PERFCHECK_DATASELECT_9STREAMS_NET}"
  value: 'IJ'
- macro: "{$PERFCHECK_DATASELECT_9STREAMS_STA}"
  value: '*'
- macro: "{$PERFCHECK_DATASELECT_9STREAMS_LOC}"
  value: '*'
- macro: "{$PERFCHECK_DATASELECT_9STREAMS_CHA}"
  value: '*'
- macro: "{$PERFCHECK_DATASELECT_9STREAMS_START}"
  value: '2016-03-02T23:01:00'
- macro: "{$PERFCHECK_DATASELECT_9STREAMS_END}"
  value: '2016-03-02T23:02:00'
- macro: "{$PERFCHECK_DATASELECT_54STREAMS_NET}"
  value: 'KO'
- macro: "{$PERFCHECK_DATASELECT_54STREAMS_STA}"
  value: '*'
- macro: "{$PERFCHECK_DATASELECT_54STREAMS_LOC}"
  value: '*'
- macro: "{$PERFCHECK_DATASELECT_54STREAMS_CHA}"
  value: 'HH*'
- macro: "{$PERFCHECK_DATASELECT_54STREAMS_START}"
  value: '2012-05-05T00:01:00'
- macro: "{$PERFCHECK_DATASELECT_54STREAMS_END}"
  value: '2012-05-05T00:02:00'
- macro: "{$PERFCHECK_DATASELECT_320STREAMS_NET}"
  value: '6G,KO,TL'
- macro: "{$PERFCHECK_DATASELECT_320STREAMS_STA}"
  value: '*'
- macro: "{$PERFCHECK_DATASELECT_320STREAMS_LOC}"
  value: '*'
- macro: "{$PERFCHECK_DATASELECT_320STREAMS_CHA}"
  value: 'BHN,BHZ,HHN,HH2'
- macro: "{$PERFCHECK_DATASELECT_320STREAMS_START}"
  value: '2014-03-06T00:01:00'
- macro: "{$PERFCHECK_DATASELECT_320STREAMS_END}"
  value: '2014-03-06T00:02:00'
- macro: "{$PERFCHECK_DATASELECT_1STREAM15DAYS_NET}"
  value: 'KO'
- macro: "{$PERFCHECK_DATASELECT_1STREAM15DAYS_STA}"
  value: 'GULA'
- macro: "{$PERFCHECK_DATASELECT_1STREAM15DAYS_LOC}"
  value: '*'
- macro: "{$PERFCHECK_DATASELECT_1STREAM15DAYS_CHA}"
  value: 'HH?'
- macro: "{$PERFCHECK_DATASELECT_1STREAM15DAYS_START}"
  value: '2012-06-04T00:00:00'
- macro: "{$PERFCHECK_DATASELECT_1STREAM15DAYS_END}"
  value: '2012-06-19T00:00:00'
- macro: "{$PERFCHECK_WFCATALOG_9STREAMS_NET}"
  value: 'IJ'
- macro: "{$PERFCHECK_WFCATALOG_9STREAMS_STA}"
  value: '*'
- macro: "{$PERFCHECK_WFCATALOG_9STREAMS_LOC}"
  value: '*'
- macro: "{$PERFCHECK_WFCATALOG_9STREAMS_CHA}"
  value: '*'
- macro: "{$PERFCHECK_WFCATALOG_9STREAMS_START}"
  value: '2016-03-02T23:01:00'
- macro: "{$PERFCHECK_WFCATALOG_9STREAMS_END}"
  value: '2016-03-02T23:02:00'
- macro: "{$PERFCHECK_WFCATALOG_54STREAMS_NET}"
  value: 'KO'
- macro: "{$PERFCHECK_WFCATALOG_54STREAMS_STA}"
  value: '*'
- macro: "{$PERFCHECK_WFCATALOG_54STREAMS_LOC}"
  value: '*'
- macro: "{$PERFCHECK_WFCATALOG_54STREAMS_CHA}"
  value: 'HH*'
- macro: "{$PERFCHECK_WFCATALOG_54STREAMS_START}"
  value: '2012-05-05T00:01:00'
- macro: "{$PERFCHECK_WFCATALOG_54STREAMS_END}"
  value: '2012-05-05T00:02:00'
- macro: "{$PERFCHECK_WFCATALOG_320STREAMS_NET}"
  value: '*'
- macro: "{$PERFCHECK_WFCATALOG_320STREAMS_STA}"
  value: '*'
- macro: "{$PERFCHECK_WFCATALOG_320STREAMS_LOC}"
  value: '*'
- macro: "{$PERFCHECK_WFCATALOG_320STREAMS_CHA}"
  value: '*'
- macro: "{$PERFCHECK_WFCATALOG_320STREAMS_START}"
  value: '*'
- macro: "{$PERFCHECK_WFCATALOG_320STREAMS_END}"
  value: '*'
- macro: "{$PERFCHECK_WFCATALOG_1STREAM15DAYS_NET}"
  value: '*'
- macro: "{$PERFCHECK_WFCATALOG_1STREAM15DAYS_STA}"
  value: '*'
- macro: "{$PERFCHECK_WFCATALOG_1STREAM15DAYS_LOC}"
  value: '*'
- macro: "{$PERFCHECK_WFCATALOG_1STREAM15DAYS_CHA}"
  value: '*'
- macro: "{$PERFCHECK_WFCATALOG_1STREAM15DAYS_START}"
  value: '*'
- macro: "{$PERFCHECK_WFCATALOG_1STREAM15DAYS_END}"
  value: '*'
- macro: "{$PERFCHECK_AVAILABILITY_9STREAMS_NET}"
  value: 'IJ'
- macro: "{$PERFCHECK_AVAILABILITY_9STREAMS_STA}"
  value: '*'
- macro: "{$PERFCHECK_AVAILABILITY_9STREAMS_LOC}"
  value: '*'
- macro: "{$PERFCHECK_AVAILABILITY_9STREAMS_CHA}"
  value: '*'
- macro: "{$PERFCHECK_AVAILABILITY_9STREAMS_START}"
  value: '2016-03-02T00:01:00'
- macro: "{$PERFCHECK_AVAILABILITY_9STREAMS_END}"
  value: '2016-03-02T23:59:00'
- macro: "{$PERFCHECK_AVAILABILITY_54STREAMS_NET}"
  value: 'KO'
- macro: "{$PERFCHECK_AVAILABILITY_54STREAMS_STA}"
  value: '*'
- macro: "{$PERFCHECK_AVAILABILITY_54STREAMS_LOC}"
  value: '*'
- macro: "{$PERFCHECK_AVAILABILITY_54STREAMS_CHA}"
  value: 'HH*'
- macro: "{$PERFCHECK_AVAILABILITY_54STREAMS_START}"
  value: '2012-05-05T00:01:00'
- macro: "{$PERFCHECK_AVAILABILITY_54STREAMS_END}"
  value: '2012-05-05T23:59:00'
- macro: "{$PERFCHECK_AVAILABILITY_320STREAMS_NET}"
  value: '6G,KO,TL'
- macro: "{$PERFCHECK_AVAILABILITY_320STREAMS_STA}"
  value: '*'
- macro: "{$PERFCHECK_AVAILABILITY_320STREAMS_LOC}"
  value: '*'
- macro: "{$PERFCHECK_AVAILABILITY_320STREAMS_CHA}"
  value: 'BHN,BHZ,HHN,HH2'
- macro: "{$PERFCHECK_AVAILABILITY_320STREAMS_START}"
  value: '2014-03-06T00:01:00'
- macro: "{$PERFCHECK_AVAILABILITY_320STREAMS_END}"
  value: '2014-03-06T23:59:00'
- macro: "{$PERFCHECK_AVAILABILITY_1STREAM15DAYS_NET}"
  value: 'KO'
- macro: "{$PERFCHECK_AVAILABILITY_1STREAM15DAYS_STA}"
  value: 'GULA'
- macro: "{$PERFCHECK_AVAILABILITY_1STREAM15DAYS_LOC}"
  value: '*'
- macro: "{$PERFCHECK_AVAILABILITY_1STREAM15DAYS_CHA}"
  value: 'HH?'
- macro: "{$PERFCHECK_AVAILABILITY_1STREAM15DAYS_START}"
  value: '2012-06-04T00:00:00'
- macro: "{$PERFCHECK_AVAILABILITY_1STREAM15DAYS_END}"
  value: '2012-06-19T00:00:00'
- macro: "{$PERFCHECK_STATION_9STREAMS_NET}"
  value: 'IJ'
- macro: "{$PERFCHECK_STATION_9STREAMS_STA}"
  value: '*'
- macro: "{$PERFCHECK_STATION_9STREAMS_LOC}"
  value: '*'
- macro: "{$PERFCHECK_STATION_9STREAMS_CHA}"
  value: '*'
- macro: "{$PERFCHECK_STATION_9STREAMS_START}"
  value: '2016-03-01T23:01:00'
- macro: "{$PERFCHECK_STATION_9STREAMS_END}"
  value: '2016-03-01T23:02:00'
- macro: "{$PERFCHECK_STATION_54STREAMS_NET}"
  value: 'KO'
- macro: "{$PERFCHECK_STATION_54STREAMS_STA}"
  value: '*'
- macro: "{$PERFCHECK_STATION_54STREAMS_LOC}"
  value: '*'
- macro: "{$PERFCHECK_STATION_54STREAMS_CHA}"
  value: 'HH*'
- macro: "{$PERFCHECK_STATION_54STREAMS_START}"
  value: '2012-05-05T23:01:00'
- macro: "{$PERFCHECK_STATION_54STREAMS_END}"
  value: '2012-05-05T23:02:00'
- macro: "{$PERFCHECK_STATION_320STREAMS_NET}"
  value: '*'
- macro: "{$PERFCHECK_STATION_320STREAMS_STA}"
  value: '*'
- macro: "{$PERFCHECK_STATION_320STREAMS_LOC}"
  value: '*'
- macro: "{$PERFCHECK_STATION_320STREAMS_CHA}"
  value: '*'
- macro: "{$PERFCHECK_STATION_320STREAMS_START}"
  value: '*'
- macro: "{$PERFCHECK_STATION_320STREAMS_END}"
  value: '*'
