- macro: "{$NODE}"
  value: 'NIEP'
- macro: "{$ENDPOINT}"
  value: 'eida-sc3.infp.ro'
- macro: "{$ROUTINGFILE}"
  value: 'eidaws/routing/1/routing.xml'
- macro: "{$ONLINECHECK_NET}"
  value: 'RO'
- macro: "{$ONLINECHECK_STA}"
  value: 'LEOM'
- macro: "{$ONLINECHECK_LOC}"
  value: ''
- macro: "{$ONLINECHECK_CHA}"
  value: 'HHZ'
- macro: "{$ONLINECHECK_START}"
  value: '2023-01-01T00:00:00'
- macro: "{$ONLINECHECK_END}"
  value: '2017-01-01T00:00:05'
- macro: "{$PERFCHECK_DATASELECT_9STREAMS_NET}"
  value: 'RO'
- macro: "{$PERFCHECK_DATASELECT_9STREAMS_STA}"
  value: 'PLOR1,PLOR2,PLOR3'
- macro: "{$PERFCHECK_DATASELECT_9STREAMS_LOC}"
  value: '*'
- macro: "{$PERFCHECK_DATASELECT_9STREAMS_CHA}"
  value: 'HH?'
- macro: "{$PERFCHECK_DATASELECT_9STREAMS_START}"
  value: '2017-05-20T00:01:00'
- macro: "{$PERFCHECK_DATASELECT_9STREAMS_END}"
  value: '2017-05-20T00:02:00'
- macro: "{$PERFCHECK_DATASELECT_54STREAMS_NET}"
  value: 'RO,BS'
- macro: "{$PERFCHECK_DATASELECT_54STREAMS_STA}"
  value: '*'
- macro: "{$PERFCHECK_DATASELECT_54STREAMS_LOC}"
  value: '*'
- macro: "{$PERFCHECK_DATASELECT_54STREAMS_CHA}"
  value: 'HHE'
- macro: "{$PERFCHECK_DATASELECT_54STREAMS_START}"
  value: '2017-05-20T00:01:00'
- macro: "{$PERFCHECK_DATASELECT_54STREAMS_END}"
  value: '2017-05-20T00:02:00'
- macro: "{$PERFCHECK_DATASELECT_320STREAMS_NET}"
  value: 'RO,BS'
- macro: "{$PERFCHECK_DATASELECT_320STREAMS_STA}"
  value: '*'
- macro: "{$PERFCHECK_DATASELECT_320STREAMS_LOC}"
  value: '*'
- macro: "{$PERFCHECK_DATASELECT_320STREAMS_CHA}"
  value: 'HHE,HHN,HHZ,HNE,HNN,HNZ'
- macro: "{$PERFCHECK_DATASELECT_320STREAMS_START}"
  value: '2013-05-22T00:01:00'
- macro: "{$PERFCHECK_DATASELECT_320STREAMS_END}"
  value: '2013-05-22T00:02:00'
- macro: "{$PERFCHECK_DATASELECT_1STREAM15DAYS_NET}"
  value: 'RO'
- macro: "{$PERFCHECK_DATASELECT_1STREAM15DAYS_STA}"
  value: 'GZR'
- macro: "{$PERFCHECK_DATASELECT_1STREAM15DAYS_LOC}"
  value: '*'
- macro: "{$PERFCHECK_DATASELECT_1STREAM15DAYS_CHA}"
  value: 'HH?'
- macro: "{$PERFCHECK_DATASELECT_1STREAM15DAYS_START}"
  value: '2012-06-04T00:00:00'
- macro: "{$PERFCHECK_DATASELECT_1STREAM15DAYS_END}"
  value: '2012-06-19T00:00:00'
- macro: "{$PERFCHECK_WFCATALOG_9STREAMS_NET}"
  value: 'RO'
- macro: "{$PERFCHECK_WFCATALOG_9STREAMS_STA}"
  value: 'PLOR1,PLOR2,PLOR3'
- macro: "{$PERFCHECK_WFCATALOG_9STREAMS_LOC}"
  value: '*'
- macro: "{$PERFCHECK_WFCATALOG_9STREAMS_CHA}"
  value: 'HH?'
- macro: "{$PERFCHECK_WFCATALOG_9STREAMS_START}"
  value: '2017-05-20T00:01:00'
- macro: "{$PERFCHECK_WFCATALOG_9STREAMS_END}"
  value: '2017-05-20T00:02:00'
- macro: "{$PERFCHECK_WFCATALOG_54STREAMS_NET}"
  value: 'RO,BS'
- macro: "{$PERFCHECK_WFCATALOG_54STREAMS_STA}"
  value: '*'
- macro: "{$PERFCHECK_WFCATALOG_54STREAMS_LOC}"
  value: '*'
- macro: "{$PERFCHECK_WFCATALOG_54STREAMS_CHA}"
  value: 'HHE'
- macro: "{$PERFCHECK_WFCATALOG_54STREAMS_START}"
  value: '2017-05-20T00:01:00'
- macro: "{$PERFCHECK_WFCATALOG_54STREAMS_END}"
  value: '2017-05-20T00:02:00'
- macro: "{$PERFCHECK_WFCATALOG_320STREAMS_NET}"
  value: 'RO,BS'
- macro: "{$PERFCHECK_WFCATALOG_320STREAMS_STA}"
  value: '*'
- macro: "{$PERFCHECK_WFCATALOG_320STREAMS_LOC}"
  value: '*'
- macro: "{$PERFCHECK_WFCATALOG_320STREAMS_CHA}"
  value: 'HHE,HHN,HHZ,HNE,HNN,HNZ'
- macro: "{$PERFCHECK_WFCATALOG_320STREAMS_START}"
  value: '2013-05-22T00:01:00'
- macro: "{$PERFCHECK_WFCATALOG_320STREAMS_END}"
  value: '2013-05-22T00:02:00'
- macro: "{$PERFCHECK_WFCATALOG_1STREAM15DAYS_NET}"
  value: 'RO'
- macro: "{$PERFCHECK_WFCATALOG_1STREAM15DAYS_STA}"
  value: 'GZR'
- macro: "{$PERFCHECK_WFCATALOG_1STREAM15DAYS_LOC}"
  value: '--'
- macro: "{$PERFCHECK_WFCATALOG_1STREAM15DAYS_CHA}"
  value: 'HH?'
- macro: "{$PERFCHECK_WFCATALOG_1STREAM15DAYS_START}"
  value: '2012-06-04T00:00:00'
- macro: "{$PERFCHECK_WFCATALOG_1STREAM15DAYS_END}"
  value: '2012-06-19T00:00:00'
- macro: "{$PERFCHECK_AVAILABILITY_9STREAMS_NET}"
  value: 'RO'
- macro: "{$PERFCHECK_AVAILABILITY_9STREAMS_STA}"
  value: 'PLOR1,PLOR2,PLOR3'
- macro: "{$PERFCHECK_AVAILABILITY_9STREAMS_LOC}"
  value: '*'
- macro: "{$PERFCHECK_AVAILABILITY_9STREAMS_CHA}"
  value: 'HH?'
- macro: "{$PERFCHECK_AVAILABILITY_9STREAMS_START}"
  value: '2017-05-20T00:01:00'
- macro: "{$PERFCHECK_AVAILABILITY_9STREAMS_END}"
  value: '2017-05-20T23:59:00'
- macro: "{$PERFCHECK_AVAILABILITY_54STREAMS_NET}"
  value: 'RO,BS'
- macro: "{$PERFCHECK_AVAILABILITY_54STREAMS_STA}"
  value: '*'
- macro: "{$PERFCHECK_AVAILABILITY_54STREAMS_LOC}"
  value: '*'
- macro: "{$PERFCHECK_AVAILABILITY_54STREAMS_CHA}"
  value: 'HHE'
- macro: "{$PERFCHECK_AVAILABILITY_54STREAMS_START}"
  value: '2017-05-20T00:01:00'
- macro: "{$PERFCHECK_AVAILABILITY_54STREAMS_END}"
  value: '2017-05-20T23:59:00'
- macro: "{$PERFCHECK_AVAILABILITY_320STREAMS_NET}"
  value: 'RO,BS'
- macro: "{$PERFCHECK_AVAILABILITY_320STREAMS_STA}"
  value: '*'
- macro: "{$PERFCHECK_AVAILABILITY_320STREAMS_LOC}"
  value: '*'
- macro: "{$PERFCHECK_AVAILABILITY_320STREAMS_CHA}"
  value: 'HHE,HHN,HHZ,HNE,HNN,HNZ'
- macro: "{$PERFCHECK_AVAILABILITY_320STREAMS_START}"
  value: '2013-05-22T00:01:00'
- macro: "{$PERFCHECK_AVAILABILITY_320STREAMS_END}"
  value: '2013-05-22T23:59:00'
- macro: "{$PERFCHECK_AVAILABILITY_1STREAM15DAYS_NET}"
  value: 'RO'
- macro: "{$PERFCHECK_AVAILABILITY_1STREAM15DAYS_STA}"
  value: 'GZR'
- macro: "{$PERFCHECK_AVAILABILITY_1STREAM15DAYS_LOC}"
  value: '*'
- macro: "{$PERFCHECK_AVAILABILITY_1STREAM15DAYS_CHA}"
  value: 'HH?'
- macro: "{$PERFCHECK_AVAILABILITY_1STREAM15DAYS_START}"
  value: '2012-06-04T00:00:00'
- macro: "{$PERFCHECK_AVAILABILITY_1STREAM15DAYS_END}"
  value: '2012-06-19T00:00:00'
- macro: "{$PERFCHECK_STATION_9STREAMS_NET}"
  value: 'RO'
- macro: "{$PERFCHECK_STATION_9STREAMS_STA}"
  value: 'PLOR1,PLOR2,PLOR3'
- macro: "{$PERFCHECK_STATION_9STREAMS_LOC}"
  value: '*'
- macro: "{$PERFCHECK_STATION_9STREAMS_CHA}"
  value: 'HH?'
- macro: "{$PERFCHECK_STATION_9STREAMS_START}"
  value: '2017-05-22T23:01:00'
- macro: "{$PERFCHECK_STATION_9STREAMS_END}"
  value: '2017-05-22T23:02:00'
- macro: "{$PERFCHECK_STATION_54STREAMS_NET}"
  value: 'RO,BS'
- macro: "{$PERFCHECK_STATION_54STREAMS_STA}"
  value: '*'
- macro: "{$PERFCHECK_STATION_54STREAMS_LOC}"
  value: '*'
- macro: "{$PERFCHECK_STATION_54STREAMS_CHA}"
  value: 'HHE'
- macro: "{$PERFCHECK_STATION_54STREAMS_START}"
  value: '2017-05-20T00:01:00'
- macro: "{$PERFCHECK_STATION_54STREAMS_END}"
  value: '2017-05-20T00:02:00'
- macro: "{$PERFCHECK_STATION_320STREAMS_NET}"
  value: 'RO,BS'
- macro: "{$PERFCHECK_STATION_320STREAMS_STA}"
  value: '*'
- macro: "{$PERFCHECK_STATION_320STREAMS_LOC}"
  value: '*'
- macro: "{$PERFCHECK_STATION_320STREAMS_CHA}"
  value: 'HHE,HHN,HHZ,HNE,HNN,HNZ'
- macro: "{$PERFCHECK_STATION_320STREAMS_START}"
  value: '2013-05-22T23:01:00'
