---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: wsdataselect
    context: {{ .Values.context }}
  name: {{ include "shibboleth-sp.fullname" . }}
data:
  {{- range $key, $val := .Values.config }}
  {{ $key }}: "{{ $val }}"
  {{- end }}
