---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "shibboleth-sp.labels" . | nindent 8 }}
    {{- with .Values.podLabels }}
    {{- toYaml . | nindent 8 }}
    {{- end }}
  name: {{ include "shibboleth-sp.fullname" . }}
data:
  {{- range $key, $val := .Values.config }}
  {{ $key }}: "{{ $val }}"
  {{- end }}
