ansible_httpapi_pass: ENC[AES256_GCM,data:a1+bZS5CNfIz1RXg,iv:H7RddWZYNm9U2THuymJa7LEmevC3ZX8bLxvu/yB8yLs=,tag:IA8Hc9vKyJ6Q4f9qPUvRhQ==,type:str]
ansible_zabbix_token: ENC[AES256_GCM,data:JTo3j8p0csw27oRBc9Di0EE8zacgzNjJUmW5dUNOfPajKO3oquDhqIslAinY/iDbv63/MwGQbfFOa/W4GDy0EQ==,iv:UZsWRuG4wulGaSVC8gs59F6JTFTBuyKsedLXzFx7TaY=,tag:VCWnb1jyOZ/sjX/2FKTrTw==,type:str]
ansible_grafana_token: ENC[AES256_GCM,data:JmbiYgrWHlP772yJ6NXOTHMKJxbu1oW9+/6EsRDbTbJvI+2KzXP+70xrddRChA==,iv:QQlb9qCL6oVa4hWP005OVMR+FSJxH2HhY1LtVJEbZ2Q=,tag:Jg5GUln/cqdFY/aNbAGtSw==,type:str]
zabbix_grafana_token: ENC[AES256_GCM,data:R//TvMel9aSOTk9WQZf0toKoFsLx95cPVkLQtj8XjoA6JRMIvZ9dHnZxYBfBdcXdhu84AkmdIZ6YbMgw2cCMCg==,iv:/dYq8eyDJCgyPD3AnGd2qnt75QcJPXpKesv4OAC61Qo=,tag:4uMlYQ/RekUv8NiK8FG+2Q==,type:str]
zabbix_grafana_pass: ENC[AES256_GCM,data:1cv/Iol7qQqnQcQY,iv:36ITStDjGcGN+0bZSfKS6uEO4T3/SbQ6dO7L07/Vs+o=,tag:g/e3v2Hk9j5ot/Bo4TS0Iw==,type:str]
zabbix_user_pass: ENC[AES256_GCM,data:wFSZ4xAxP7ljWumR,iv:L5Tq7l4aN5v8eGuVSfb8xFT9x45JjZslfHAny1PC+mE=,tag:NtlgmZFNo6MoojYbjOXPXQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-06-30T15:06:22Z"
    mac: ENC[AES256_GCM,data:zDlsa6eqT50OGjGQex7xIK383xQuzoCTb7mWt7QiSkxBnlQ6yHp9XkrbxFJlUUOTT5KF7XL/NagzOGUCs7KQkf4YnasYQ6FFLKPqAzB2/Wputlh+5lrrhVr3cdy9rLGZaA6Q79Kg1peb6DYVK8LAmyQ+k1fXwyiU69LogROJ31o=,iv:xbcorH5EcIIs20/OFGErvO7vtMQTqhX0TgMXq80VjB8=,tag:0qkgRTQOSnAMsvTiVmPXNw==,type:str]
    pgp:
        - created_at: "2026-06-30T15:06:22Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQEMA23uPS/3Y9M2AQf+LhEsoSCbeHkVxao4t1fLiVcSLpgUIRCOYW3jxLWN6dvh
            hbvew5gofzir9VTDbQadFTX49+fytH/bDj9oyazpUC7HzDu/34LHN5AWRWVDhWNQ
            dcdCpsQ2XbkUjacWWSG21F3heKZPZiTETaCxBTecydi9tm1KBzQQaC0EZozEojHR
            syZ5FwFMqZBzbqdqLXS6ZSNgb6t8Yq472fkYu24gM4aI63d8DSnR+ueWcIL2EV98
            OXN8RkQ1U89Bs4H08GUGtIAhaAI3eWOt7hNlVc5MCXR4/BETqVz0frHhP86azLaT
            pCIQZ3dVsK/jArl9DzyW3beZ343rvF1mTz8/0Yom4tJeAVLKLCtXe3F/2ydnyP8o
            ku0jVlu3kbkF8Q4NB5f+TFY/6moBCohiTbtfGcD/Qh72MdmFsDMgPQGXvfK2OUsL
            1MrUj7ju6i5RdNwWZv+/xVbGkY4NE+SkHdUniFQ2DA==
            =PUK0
            -----END PGP MESSAGE-----
          fp: C83ECA1E0B9D719C7FA2470F18E4F5A58801E669
    encrypted_regex: (password|ansible_httpapi_pass|ansible_zabbix_token|ansible_grafana_token|zabbix_grafana_token|zabbix_grafana_pass|zabbix_user_pass|adminPassword)
    mac_only_encrypted: true
    version: 3.9.2
