ansible_httpapi_pass: ENC[AES256_GCM,data:qGz6JWcuILIMo7RG,iv:o0GSq+76nHCu9v2F85P8gohgMIvX5c9kxWBQgyfxbH0=,tag:EUS87kr/Uxxh/OxKBaZSew==,type:str]
ansible_zabbix_token: ENC[AES256_GCM,data:WXv4hcZYCU9XPDY6KMO76aeizV3zWuR2VFxCBzucs1eBvYaOFXG2s+Sep/fsGAtGlwL8nWCbcLwUr7+5XUdOsA==,iv:cABgzZFXA5n3B2qOZTQbtvtxm9MLdsvOxgshZeYxYVM=,tag:AejP9kFH++ANHrycOcOByA==,type:str]
ansible_grafana_token: ENC[AES256_GCM,data:S18MflkZ/0NYhq4Ytg9/UqMNaCtdE2Qj0mlTXp1CAYF9RklsBwqxwmVmigeveA==,iv:cCPWJShS3ULnHIVJstw5e9maIV35Uacl/h5SpgEsuvw=,tag:rg+kLuLT+6Polb0TLqB7Cw==,type:str]
zabbix_grafana_token: ENC[AES256_GCM,data:ckiEACmIOezxTQSW7NUt5gxcujblgJBxalDqrrC2jhVDVnMslLwBeuuzhF8pBQ+Ip7qSVnBn2kTNF6/Zdzj2UQ==,iv:O1FY5+CTk7ayPIaCClLkil3jeodFCUnTZMt6cJme8/o=,tag:bAw62uq/jpzURk6hSJTVqw==,type:str]
zabbix_grafana_pass: ENC[AES256_GCM,data:Lw3P6J/64S0A4/kw,iv:PpGkWE+zreq4S9IU/FBTD8q9P37Zjar4YeN0LYUkzVs=,tag:dwP4ZLqKDeiIdjX92XpPXQ==,type:str]
zabbix_user_pass: ENC[AES256_GCM,data:tiWN0w29C/sPyeck,iv:S+Sddc7mO3weMg9gpZT0JY8fPrdok6BQ9CKhlV6XSL4=,tag:gjcCEHvojchgIXMnpbXejw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-06-30T15:06:17Z"
    mac: ENC[AES256_GCM,data:ixi0amCb7lh1ai0nbVZjplzGaKelzX6HGK5Hv1Yi0WP4xG3uPMH6wQp+VdUXAz3yvIycmAre/URPcJUpNr6vAOzeLeaqPTYiL2jcDo8pEnjWa9AeCSkU0FxX3JjxcfnoN5pL3PtDXK8Yj5/C95uKVT72JLhpKY1qoCHWQJdQO2Q=,iv:kK4VD332jbQ2WepJN8FApAlQWJyOg1gqCJRz2yEdY/0=,tag:liI8XZOHGesSZYdWa0jgKw==,type:str]
    pgp:
        - created_at: "2026-06-30T15:06:17Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQEMA23uPS/3Y9M2AQgAw1FD28WLdJI1OMtjL5xs0ljdDoo3ugCC62iwXhgk8hXY
            Jq0inmecVPX8zeMC/8p6TKulSNO3Koauh1FZrlWACwAmzL+aSNhMvu2MbZ/rxYPN
            7R2S0Xe7kud3be4OJpxxFFT9VXFvgcl2QvhW/7YNzv5+oeWT4UUGn8i6xNwns7Dd
            20Xtc24VUpL1EfXffVh+sysWmRws7EHgeRbF1idmIZdc28omFfj0lR0ImrVD8its
            p0+HGGvgPqZDKPNiOIxrgYeBJOitdUy4K+JPeGZ8qx/Tbvg1EUJvXROTjER1k+zG
            1p/u5KOG3T1mNTRt9bxeNTbrODBjjVs5QvHI0B0xPNJcARFLdwwXQCGkcVKbyivc
            HmSsahoc0Zr9xDDDaMwWuDlT4dL4J5mvh9DkqNlSn4ubtkce7Ep8ZbiThhRlEuOH
            j30ah7NCnp4+J1VIpbwFgmhy6xFsKf9/6MiZnG0=
            =DzIO
            -----END PGP MESSAGE-----
          fp: C83ECA1E0B9D719C7FA2470F18E4F5A58801E669
    encrypted_regex: (password|ansible_httpapi_pass|ansible_zabbix_token|ansible_grafana_token|zabbix_grafana_token|zabbix_grafana_pass|zabbix_user_pass|adminPassword)
    mac_only_encrypted: true
    version: 3.9.2
