ansible_httpapi_pass: ENC[AES256_GCM,data:51rQeJeDocI6PEbk,iv:ksiFNlAVvS6+l1uQH1JccEtAFYMjXtOrAJRiclO35lg=,tag:71R8tnfLSk/r77j6iq3K/Q==,type:str]
ansible_zabbix_token: ENC[AES256_GCM,data:y+yAY1jE37C9gFmUIRaaq9MHlSZ1faWV6m258gyHm6M+vqlRurawqPK8cJUGhXGTutRJqKWHCPH5PL541UPVdw==,iv:Dr1KLj0fTlHyq5Ij2jE90vQMtN/vP0XX/592fTvsTGU=,tag:YziRGJ4rwlIogZqW2YeWUQ==,type:str]
ansible_grafana_token: ENC[AES256_GCM,data:HrTJkk+1k16kerDsfwvFHzHVlNq5a1+AwEFfqxrDqLFLl+dVLwrbn1Jb1bWH+w==,iv:ur8IfDucwUipcMcTHCl9qYWahq0Iz1845R569M1gBjQ=,tag:MhQ5k6wd4/4t90cJC5uCQQ==,type:str]
zabbix_grafana_token: ENC[AES256_GCM,data:XoA6GHOhpNhPvvug/6hWoUYNXOJWcaYCIb+s6n3oP+bZ5TdAmoGNskeWY7814GjjR+1xpbBD+YfQe6h5ZL1uPw==,iv:VNnhC72ryIwY4ATjrwJQcjTgLU5yce6QN5NAJrdwiVU=,tag:NYagyfRsMe881GxyGHTZUg==,type:str]
zabbix_grafana_pass: ENC[AES256_GCM,data:tkgSVZGeMjQZrolx,iv:BzmPfuXja1ca1zqztDpevYZL5s6JXiriJ70IwvtynRA=,tag:mTxPAdhXskFcy3kSdK5KFg==,type:str]
zabbix_user_pass: ENC[AES256_GCM,data:ORE9AB/6nrL/6r0f,iv:5UnZNPGtUBvEWQKWfMsIGS1MzS/4+5QI1ULXBzrCof4=,tag:RwWaaWO1BC9SsW+RAO1mjA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: "2025-08-01T12:58:01Z"
  mac: ENC[AES256_GCM,data:M4Y196BKcCRpworVpuTTp3NCoTHr4ejTRYH7S8Zfap+oeZUYHbZVX3f0IvbWaU0LZ/5/QF3iT439ocm5puhRg9ybMAUzYhZb31KABNeoWsHf+uv4PtfoKr/kdfMHy8NsqmD5Oe0FSvLoHkEd9EuWiC+qsSTOMk/j1W9jYquGRkg=,iv:1e39T42HStSr214OjuY/+Emvu7ntVefhHAPxQQ5/LwQ=,tag:lFOBBMuTTc2QV3c32zWJmw==,type:str]
  pgp:
  - created_at: "2025-08-01T12:58:01Z"
    enc: |-
      -----BEGIN PGP MESSAGE-----

      hQEMA23uPS/3Y9M2AQgAt6sMnFCUOHN2MuYjtuOAKCt3P6sh3aX9j/1J3XdKJXsP
      LonEZiQPgay1mDq5a+KTQjebQpYtZuAZgpEKyc7OGOMpY34m2ieIEJTvmwTLIAPW
      uSOEAuKeGHaFTN+oKtdn5vJC860J9q7BvnyGR/i0mvrCb5ehfaz5pFHaqy9sZkEF
      CgKzTdsVRxK2lnXuDo4vGh5Y2ZkhZeDq5ZTn+dns1IBrwX2yQPdeB1ZXwGpyB6Pk
      jUcJSRRgvVdtGSvepJc8YnciZ3ZH75FMeIz6DfS/ZlC5GCEQ/koOZgJkq47UNN4s
      QXcboJTlNN8e/iQQvB33hg1Vh+FaicRptPuvvGZa+dJeAdHzbKD7JIyA9CZ5acA9
      LvOpgqKoNHB9rjZRQUcRkKsESotuy1zPdtMKgjrvMybe164S1K6cBz8f7ZWCYWRU
      WnL3J8QuqD0SLHvP06hPxn+ZZNrzuIIaYShW/LdLxw==
      =ZJPJ
      -----END PGP MESSAGE-----
    fp: C83ECA1E0B9D719C7FA2470F18E4F5A58801E669
  encrypted_regex: (password|ansible_httpapi_pass|ansible_zabbix_token|ansible_grafana_token|zabbix_grafana_token|zabbix_grafana_pass|zabbix_user_pass|adminPassword)
  mac_only_encrypted: true
  version: 3.9.2
