ansible_httpapi_pass: ENC[AES256_GCM,data:LGQUjno3MPpYd9MV,iv:W7q0Aml+MNc2O7ZcXkgtrGR7438pU5VfjZPe9e3PShU=,tag:kTEGrl98fxfo1ig7zbiAig==,type:str]
ansible_zabbix_token: ENC[AES256_GCM,data:z5c4V7YDTbkKyYifC+gBtjc0eKPudQHFjXGSajsSt7HJQZoCyTynzRq3vBcVCKr5mCljfJ2+XVPsGN+B0UY2MQ==,iv:wdIAFZX6WanFCaVWlD6p0f5SbnC3vhsHnp0cwDas1xI=,tag:bz2M1044jnGDlaUH3JBzXg==,type:str]
ansible_grafana_token: ENC[AES256_GCM,data:RSao7T9XbBOiQn+pPWewQW+C5wY9FqYe/YzCmYB5rAHsct/3exfWwUuWCE6cnQ==,iv:ZpzqpNNYqYKClttY6pVNintcblULu/aj66gmlMd1KlM=,tag:ohQQ3XSaZm8KzvxL7+Vl4g==,type:str]
zabbix_grafana_token: ENC[AES256_GCM,data:sSmT+8W4GLiXG2ZSPpPrintSpAIR47zGEOTdf0Q8O7LVj8oI1qtSXc9voawd+3fCLo8FLoou1Ma05r0iBieUKg==,iv:UAH6Zbi06cS5nGfKgPBIh27BNbnPVM0h/RYact8n/HM=,tag:sNrWua1IODkIjHCYheF1+g==,type:str]
zabbix_grafana_pass: ENC[AES256_GCM,data:BfQ2UfrjZMGIBEv0,iv:+2ohtXUYQAmmgAYTzR5lPG8yl2tv5V1yJpfudjqaWdg=,tag:A/wLJt3iP0oMzcfHl5GApw==,type:str]
zabbix_user_pass: ENC[AES256_GCM,data:jJFa7fOSg9IgwTg1,iv:71T6BJzDz9Gt71bu4RuivYIlt/wRtiwPOPW8StFx5dE=,tag:1QoeSlrdddSHijEtGhZdnQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-07-22T12:28:19Z"
    mac: ENC[AES256_GCM,data:gzHY+JX75cFT0IiW2Qy+CWAO+la+POgDNWrloYDfgwtuBrXKiJTOT1tE5U4Q5QvsCYxuFFqXdr4K9AETX8ANjlKPdZ1YGwwPOS5aRnzisNvjfBEAV0kFKNVC9TWKMUHpY6uNWKRJHtdBMepM979S87ARfCpi+vJsy6pE9t+p3Es=,iv:4Daz6e5ZbIk2KUarsaHIcEo/yn/xIL2V55tcdZ/ZRLM=,tag:Cd4/rewJ9eMbsaZVf3ZWCg==,type:str]
    pgp:
        - created_at: "2026-07-22T12:28:19Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQEMA23uPS/3Y9M2AQf/X4AwPc3muFZ7n+G65HEGCS+16rjg/KS0deG3JGo3Q9y/
            OrrAv9IjmFsFjGH2J34jRN9f4IHhbLaDpCrXu6qAOEQxXnFbv2pBeQ+GtmLFej/L
            wZnCYU7CohvQN+CWU8kv8PDyHoFDBJllymIBI5XwvNYPKodVMQp8rUJTDiYmpeaG
            C7cesXtKsTp6h9UkZ9Uqv4u+kVORgIvjIJMtYCLnWJSXU19v2nzQrvAIcCTBi78E
            efNCoCwDGJ7gYSpzs6FydMNqcr4OOm7lgDDUCR6tZTQ+xRsv6iYOjVLpd8J2u6Mp
            Yas+N0iDkq/4A4PLv8WdWUgTJvp25ndDintt764mV9JeAe9kY8bpS41jHDA6qpzV
            vc+N4+IWzEsaRbqVMWZAd8wT6sSw7BEyJBYnTTrrkJgy3WTOSdz26wS+KpUKK3oZ
            uoZzaPGkP91y38zPoexkkKYINoAiai579usrFV0Yag==
            =S5S3
            -----END PGP MESSAGE-----
          fp: C83ECA1E0B9D719C7FA2470F18E4F5A58801E669
    encrypted_regex: (password|ansible_httpapi_pass|ansible_zabbix_token|ansible_grafana_token|zabbix_grafana_token|zabbix_grafana_pass|zabbix_user_pass|adminPassword)
    mac_only_encrypted: true
    version: 3.9.2
