global:
  imageRegistry: null
  imagePullSecrets: []
grafana:
  enabled: true
  adminUser: admin
  adminPassword: ENC[AES256_GCM,data:GZg39x93qO/vFRkh,iv:A63J0m2D/LRc7dwyV+2/uwPKROq8JLUFqfHIwWYSJxU=,tag:4ya9dXt+jhJTDtA3S/douQ==,type:str]
  service:
    type: ClusterIP
    port: 3000
  ingress:
    enabled: true
    annotations: {}
    hosts:
    - host: grafana.local
      paths:
      - /
    tls: []
  persistence:
    type: pvc
    enabled: true
    storageClassName: standard
    accessModes:
    - ReadWriteOnce
    size: 10Gi
  plugins:
    enabled: true
    plugins:
    - grafana-piechart-panel
    - grafana-worldmap-panel
    - alexanderzobnin-zabbix-app
    - alexanderzobnin-zabbix-datasource
  datasources:
    enabled: true
    defaultDatasource:
      name: Zabbix
      type: alexanderzobnin-zabbix-datasource
      url: http://oculus-zabbix-zabbix-web:8888/api_jsonrpc.php
      access: proxy
      isDefault: true
      jsonData:
        username: grafana
        password: ENC[AES256_GCM,data:pf75PZ1fC2YNp5neCY+oCmMFOQ0=,iv:Z2mjrr3wyXvzZedX4EiTo871+o4KY1cL33qVp8dd5lc=,tag:BhpBTDIAl5vKAjlYp2lifg==,type:str]
  dashboards:
    enabled: true
    defaultFolderName: Default
    configMaps: []
  database:
    type: postgresql
    host: resif-pgpreprod.u-ga.fr
    port: 5432
    user: oculus
    password: ENC[AES256_GCM,data:GcAf6OCAqaWsPdYFuP9Hm3fNrS8=,iv:wRDh23UjE6Ec6Emey/CRcZ2UYexmwRJtCbF2fbYK6lQ=,tag:kYRlknIny/b9/RtYQXdhAg==,type:str]
    name: oculus_grafana
ingress:
  enabled: true
  hosts:
  - eida-oculus.resif.fr
  requests:
    cpu: 0.5
    memory: 2Gi
  limits:
    cpu: 2
    memory: 3Gi
nodeSelector: {}
tolerations: []
affinity: {}
grafana.ini:
  auth.anonymous:
    enabled: true
    org_name: Main Org.
    org_role: Viewer
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: "2025-06-24T14:19:49Z"
  mac: ENC[AES256_GCM,data:P3B2ziYOUrjsX8lSqGFUkfKpjYl6sqKKUU+8WA/nhQ8P2jkFpZ9lanZvXbKF5RKbFOMlnVh6/TkKO8fmla//bVLNR67h6XfwGwt5n6tJyE8FNkLHvgqfjWd2Z4vUgmp5yCpQEbsOUyijIIb5Bj6ypFhuoKTXff5Yhny6gVZjxcM=,iv:/juac2KNPdaO/2F+3Ax6U1trjBZXA/qzASF7eKt9fKY=,tag:EGpeuvazpR7KTvZU7PtQfw==,type:str]
  pgp:
  - created_at: "2025-06-24T14:19:49Z"
    enc: |-
      -----BEGIN PGP MESSAGE-----

      hQEMA23uPS/3Y9M2AQf+PMDMA9HkYJM0HA+4otfyZWa6H5k/JLUkwtpA6cZ9m05/
      w2Xc/vjJwBEgiziTCCuop9rlLXaRloI83yteDZU/EmyhLIjY2yTt6xOCnx1bKY0j
      GP18UTxHZAYt7sdjmDkpVLWqCbnjuj+obU4d53XHhcPQfQ+kPg7M/IXypRdTfBZe
      pBHv7h+o4IrE8QzKlcgD3zvK6WD4Yr1wyc8Mv58b1gjJac8Qpthd/rswmio9B3t4
      zZwYgs7wSi9AIhOmTnwbrk+6mkILQQa9fonucfmWP8lr7wHB2Nhp2EqboVBSMlRt
      NAu3sUF0SgMZMGE8Xmgig28DSRmK1m1H3+iwq0ZNetJeARFlI3w+cteyoOKTUY7t
      gYvsc/DuSKJPxv47/CkEcOVc52gmIPov67rUZk1GfAsTDToPTEz9jolzyMWGCVsk
      oEgW0rglUfAjkDmBUctnj4m1vREGPIP7G/cWUMfCWg==
      =rzda
      -----END PGP MESSAGE-----
    fp: C83ECA1E0B9D719C7FA2470F18E4F5A58801E669
  encrypted_regex: (password|ansible_httpapi_pass|ansible_zabbix_token|adminPassword)
  mac_only_encrypted: true
  version: 3.9.2
