adminUser: admin
ingress:
  enabled: true
  hosts:
  - eida-oculus.orfeus-eu.org
grafana.ini:
  auth.anonymous:
    enabled: true
    org_name: Main Org.
    org_role: Viewer
  plugins:
    enabled: true
  # server:
  #   root_url: eida-oculus.orfeus-eu.org
plugins:
- grafana-piechart-panel
- grafana-worldmap-panel
- alexanderzobnin-zabbix-app
