global:
  imageRegistry: null
  imagePullSecrets: []
grafana:
  enabled: true
  adminUser: admin
  adminPassword: 13uSKV2OCLE4zJvEjmEvSZfbC6sLlcWUJDyfufoc
  service:
    type: ClusterIP
    port: 3000
  ingress:
    enabled: true
    annotations: {}
    hosts:
    - host: grafana.local
      paths:
      - /
    tls: []
  dashboards:
    enabled: true
    defaultFolderName: Default
    configMaps: []
resources: null
nodeSelector: {}
tolerations: []
affinity: {}
envFromSecret: grafana-db-secret
grafana.ini:
  database:
    type: postgres
    host: resif-pgpreprod.u-ga.fr
    port: 5432
    user: oculus
    name: oculus_grafana
  auth.anonymous:
    enabled: true
    org_name: Main Org.
    org_role: Viewer
  plugins:
    enabled: true
plugins:
- grafana-piechart-panel
- grafana-worldmap-panel
- alexanderzobnin-zabbix-app
