global:
  imageRegistry: null
  imagePullSecrets: []
grafana:
  enabled: true
  adminUser: admin
  adminPassword: ENC[AES256_GCM,data:Y3m0DFaCgr3jF2p8,iv:sT41ZvNyWwGu9RFbqWZoS6c6ekcE874flMXGkFs6o5E=,tag:E73TJekiIVTdecwRilmCLA==,type:str]
  service:
    type: ClusterIP
    port: 3000
  ingress:
    enabled: true
    annotations: {}
    hosts:
    - host: grafana.local
      paths:
      - /
    tls: []
  persistence:
    type: pvc
    enabled: true
    storageClassName: standard
    accessModes:
    - ReadWriteOnce
    size: 10Gi
  plugins:
    enabled: true
    plugins:
    - grafana-piechart-panel
    - grafana-worldmap-panel
    - alexanderzobnin-zabbix-app
    - alexanderzobnin-zabbix-datasource
  datasources:
    enabled: true
    defaultDatasource:
      name: Zabbix
      type: alexanderzobnin-zabbix-datasource
      url: http://oculus-zabbix-zabbix-web:8888/api_jsonrpc.php
      access: proxy
      isDefault: true
      jsonData:
        username: grafana
        password: ENC[AES256_GCM,data:QU+RCgv6NKxKrmS9GN2BPIMf4IA=,iv:mLvY5N/tADHMAG8cFoKxY9FZkQxYmQzj1uaysV3hKcs=,tag:qlbEXh/Nl9tIK+o5mY5wpA==,type:str]
  dashboards:
    enabled: true
    defaultFolderName: Default
    configMaps: []
  database:
    type: postgresql
    host: resif-pgpreprod.u-ga.fr
    port: 5432
    user: oculus
    password: ENC[AES256_GCM,data:YrEBBi12l2z3b7/h3VHXUm/5QUo=,iv:Xlc0dfTly3JpkESb4aZvvTxXvZ8BDLPnLYwmwVe4x00=,tag:wsw1TtyJ73jmMu8EQuXHcQ==,type:str]
    name: oculus_grafana
resources:
nodeSelector: {}
tolerations: []
affinity: {}
grafana.ini:
  auth.anonymous:
    enabled: true
    org_name: Main Org.
    org_role: Viewer
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: "2025-06-24T14:19:26Z"
  mac: ENC[AES256_GCM,data:IHZ6a/pT3tcozTk0yYub/quloNkcRAHGpdJgA+chqrQx67M+nbkz6u62yyTdPBnidR1Vff6cS6MxhxQMmcim74Qp3QG5e5BgldN3f60S9Dzg9UuMp4FSbZaSoAE0pDtVDkWZfHwAGlm4s8Uj+PRjaHmtlYukz5hNcCMxOcnxT8c=,iv:AWgXSANP79hK+IOk1qYG/klvh4eYcum90/kPHDodrQk=,tag:94Zj8pfjyKGxd0uhmnlgrQ==,type:str]
  pgp:
  - created_at: "2025-06-24T14:19:25Z"
    enc: |-
      -----BEGIN PGP MESSAGE-----

      hQEMA23uPS/3Y9M2AQf+JvotIVns9nE9NcivEEWA3JhBVjM7DNbzpHmjbTMLK9m4
      wTBu+u6e4UiTyq/VmKR+M6StovN8VMXz/uMob4YbV7HIbc7dZf/VvZRQI8yNun59
      uL4G6aAAVA6ogjNf/xwxm8LpY7oONP7hJs42CJN33A7zKXDwNh/XmU7f+ikyRmKy
      PlK0k+Y0cN/P/XJPtzmPFCDL1SZhTDJXvPcWlcJHP4YNJyXRFHpyu6an9XS7c6nr
      qlbidNlcrWTWBMgoPTPT/T41IIeW4DDHqBTW3WO+S3KsTobMlDWM59pDhfhCarSf
      KjKuaHWHrRKSTp9eZW2aGcxK+lY1H6BByzYJCRGoRdJcAfCu2slDe2NWjXgFx+eH
      kiO8QF6JKEM5VkTbaD2o28ECVnTaxbto2q30Wll6AGJ0KsGZmyGC555Ous6saRhe
      NXsMaCN6xzQEgOHdaw0zRtOL7yPd1uAFUjee/U8=
      =87G5
      -----END PGP MESSAGE-----
    fp: C83ECA1E0B9D719C7FA2470F18E4F5A58801E669
  encrypted_regex: (password|ansible_httpapi_pass|ansible_zabbix_token|adminPassword)
  mac_only_encrypted: true
  version: 3.9.2
