adminUser: admin
ingress:
  enabled: true
  hosts:
  - grafana.local
grafana.ini:
  auth.anonymous:
    enabled: true
    org_name: Main Org.
    org_role: Viewer
  plugins:
    enabled: true
plugins:
- grafana-piechart-panel
- grafana-worldmap-panel
- alexanderzobnin-zabbix-app
