---
- name: Create CORS test with item HTTP agent
  hosts: localhost
  gather_facts: false
  vars_files:
    - config.yaml
    - eida_nodes.yaml
  vars:
    ansible_network_os: community.zabbix.zabbix
    ansible_connection: httpapi
    ansible_httpapi_port: 8888
    ansible_httpapi_use_ssl: false
    ansible_httpapi_validate_certs: false
    ansible_zabbix_url_path: ""
    ansible_host: localhost
    webservices:
      - fdsnws/availability
      - fdsnws/dataselect
      - fdsnws/station
      - eidaws/wfcatalog

  tasks:
    - name: Credentials Zabbix API
      delegate_to: localhost
      ansible.builtin.set_fact:
        ansible_user: ansible
        ansible_httapi_pass: "{{ ansible_httpapi_pass }}"

    - name: Set API token
      delegate_to: localhost
      ansible.builtin.set_fact:
        ansible_zabbix_token: "{{ ansible_zabbix_token }}"

    - name: Create item HTTP agent
      delegate_to: localhost
      loop: "{{ eida_nodes }}"
      community.zabbix.zabbix_item:
        name: CORS {{ webservices }}
        host_name: "{{ item.name }}"
        params:
          type: http_agent
          key: cors.check
          interval: 1m
          retrieve_mode: Headers
          url: https://{$ENDPOINT}/{{ webservices }}
          preprocessing:
            - type: regular_expressions
              params: Access-Control-Allow-Origin:\s*(.+)
              output: \1
              value_type: character
        state: present
