---
- name: Create EIDA nodes hosts in Zabbix
  hosts: localhost
  gather_facts: false
  vars_files:
    - ../files/eida_nodes.yaml
    - ../config/config_staging.yaml
  vars:
    namespace: eida-monitoring
    release_name: zbx-agent
    chart_name: zabbix/zabbix-agent
    chart_version: "1.2.0"
    zabbix_server: "localhost:8888"
  