---
- name: Import templates
  import_playbook: zbx_templates.yaml
- name: Configure autoregistration
  import_playbook: zbx_autoregistration.yaml
- name: Deploying agents
  import_playbook: deploying_agents.yaml
- name: Create users
  import_playbook: zbx_create_users.yaml
