---
- name: Deploy tests perfchecks python scrips on k8s cluster
  hosts: localhost
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python
  tasks:
    - name: Deploy script for perfchheck
      kubernetes.core.k8s:
        state: present
        namespace: eida-monitoring
        definition:
          apiVersion: batch/v1
          kind: CronJob
          metadata:
            name: oculus-perfchecks
          spec:
            suspend: false
            schedule: "0 13 * * *" # everyday at 1pm
            jobTemplate:
              spec:
                template:
                  spec:
                    restartPolicy: OnFailure
                    containers:
                      - name: oculus-perfchecks
                        image: ghcr.io/eida/oculus-perfchecks:main
                        imagePullPolicy: Always
                        env:
                        envFrom:
                          - configMapRef:
                              name: oculus-consistency-config
