---
- name: Configuration of Zabbix autoregistration
  hosts: localhost
  gather_facts: false
  vars_files:
    - ../config/config_staging.yaml
  vars:
    ansible_network_os: community.zabbix.zabbix
    ansible_connection: httpapi
    ansible_httpapi_port: 8888
    ansible_httpapi_use_ssl: false
    ansible_httpapi_validate_certs: false
    ansible_zabbix_url_path: ""
    ansible_host: localhost

  tasks:
    - name: Import Zabbix Credentials
      ansible.builtin.import_tasks: ../config/config_zabbix.yaml

    - name: Configure autoregistration
      delegate_to: localhost
      community.zabbix.zabbix_action:
        name: "EIDA nodes autoregistration"
        event_source: auto_registration
        status: enabled
        esc_period: 60
        operations:
          - type: add_host
          - type: add_to_host_group
            host_groups:
              - "Discovered hosts"
          - type: link_to_template
            templates:
              - "Template discovery"
              - "Linux by Zabbix agent"
          - type: enable_host
