---
- name: Configuration Zabbix Trigger action
  hosts: localhost
  gather_facts: false
  vars_files:
    - ../config/config_staging.yaml
    - ../files/eida_nodes.yaml
  vars:
    ansible_network_os: community.zabbix.zabbix
    ansible_connection: httpapi
    ansible_httpapi_port: 8888
    ansible_httpapi_use_ssl: false
    ansible_httpapi_validate_certs: false
    ansible_zabbix_url_path: ""
    ansible_host: localhost

  tasks:
    - name: Import Zabbix Credentials
      ansible.builtin.import_tasks: ../config/config_zabbix.yaml

    - name: Configure Trigger action
      community.zabbix.zabbix_action:
        name: "Reports EIDA problems"
        event_source: trigger
        state: present
        status: disabled
        esc_period: 1h
        eval_type: andor
        conditions:
          - type: host_template
            operator: equals
            value: "Template webservices"
        operations:
          - type: send_message
            send_to_groups: "{{ eida_nodes }}"
            media_type: "Email (HTML) EIDA"
        recovery_operations:
          - type: send_message
            send_to_groups: "{{ eida_nodes }}"
            media_type: "Email (HTML) EIDA"
        update_operations:
          - type: send_message
            send_to_groups: "{{ eida_nodes }}"
            media_type: "Email (HTML) EIDA"
        pause_symptoms: true
        notify_if_canceled: true
