---
- name: Configuration of Zabbix autoregistration
  hosts: localhost
  gather_facts: false
  vars_files:
    - ../config/config_staging.yaml
  vars:
    ansible_network_os: community.zabbix.zabbix
    ansible_connection: httpapi
    ansible_httpapi_port: 8888
    ansible_httpapi_use_ssl: false
    ansible_httpapi_validate_certs: false
    ansible_zabbix_url_path: ""
    ansible_host: localhost

  tasks:
    - name: Import Zabbix Credentials
      ansible.builtin.import_tasks: ../config/config_zabbix.yaml

    - name: Configure autoregistration
      delegate_to: localhost

