---
- name: Install Zabbix plugins (EIDA)
  hosts: localhost
  gather_facts: false
  vars_files:
    - "../config/config_{{ hostvars['localhost']['selected_environment'] | default('staging') }}.yaml"
  vars:
    ansible_network_os: community.zabbix.zabbix
    ansible_connection: httpapi
    ansible_httpapi_port: 8888
    ansible_httpapi_use_ssl: false
    ansible_httpapi_validate_certs: false
    ansible_zabbix_url_path: ""
    ansible_host: localhost

  tasks:
    - name: Import Zabbix Credentials
      ansible.builtin.import_tasks: ../config/config_zabbix.yaml

    - name: Import Zabbix templates
      delegate_to: localhost
      community.zabbix.zabbix_template:
        template_yaml: "{{ lookup('file', '../../zabbix_server/templates/zbx_export_templates.yaml') }}"
        state: present
