---
- name: Deploy EIDA Nodes in Zabbix
  hosts: localhost
  gather_facts: false
  vars_files:
    - ../config/config_staging.yaml
  vars:
    ansible_network_os: community.zabbix.zabbix
    ansible_connection: httpapi
    ansible_httpapi_port: 8888
    ansible_httpapi_use_ssl: false
    ansible_httpapi_validate_certs: false
    ansible_zabbix_url_path: ""
    ansible_host: localhost
    host_files_directory: "../../oculus-zbx-agent-deployments"

  tasks:
    - name: Import Zabbix Credentials
      ansible.builtin.import_tasks: ../config/config_zabbix.yaml

    - name: Find all YAML files
      ansible.builtin.find:
        paths: "{{ host_files_directory }}"
        patterns: "*.yaml,*.yml"
      register: host_files

    - name: Display found files
      ansible.builtin.debug:
        msg: "Found {{ host_files.files | length }} files: {{ host_files.files | map(attribute='path') | map('basename') | list }}"

    - name: Create Zabbix hosts from file names
      community.zabbix.zabbix_host:
        host_name: "{{ item.path | basename | regex_replace('\\.(yaml|yml)$', '') }}"
        host_groups:
          - "EIDA nodes"
        status: "enabled"
        state: "present"
        inventory_mode: "disabled"
      loop: "{{ host_files.files }}"
      loop_control:
        label: "{{ item.path | basename }}"
      register: host_results

    - name: Display creation results
      ansible.builtin.debug:
        msg: "Host '{{ item.item.path | basename | regex_replace('\\.(yaml|yml)$', '') }}': {{ 'Created/Updated' if item.changed else 'Already exists' }}"
      loop: "{{ host_results.results }}"
      loop_control:
        label: "{{ item.item.path | basename }}"
