---
- name: Deploy EIDA Nodes in Zabbix
  hosts: localhost
  gather_facts: false
  vars_files:
    - "../config/config_{{ hostvars['localhost']['selected_environment'] | default('staging') }}.yaml"
  vars:
    ansible_network_os: community.zabbix.zabbix
    ansible_connection: httpapi
    ansible_httpapi_port: 8888
    ansible_httpapi_use_ssl: false
    ansible_httpapi_validate_certs: false
    ansible_zabbix_url_path: ""
    ansible_host: localhost
    host_files_directory: "../../eida_nodes"
    macros_output_directory: "../files/macros"

  tasks:
    - name: Import Zabbix Credentials
      ansible.builtin.import_tasks: ../config/config_zabbix.yaml

    - name: Create macros output directory
      ansible.builtin.file:
        path: "{{ macros_output_directory }}"
        state: directory
        mode: '0755'

    - name: Find all YAML files
      ansible.builtin.find:
        paths: "{{ host_files_directory }}"
        patterns: "*.yaml,*.yml"
      register: host_files

    - name: Display found files
      ansible.builtin.debug:
        msg: "Found {{ host_files.files | length }} files: {{ host_files.files | map(attribute='path') | map('basename') | list }}"

    - name: Execute values_to_macros.py and save output
      ansible.builtin.shell:
        cmd: "python ../../scripts/values_to_macros.py {{ item.path }} > {{ macros_output_directory }}/{{ item.path | basename }}"
        chdir: "{{ playbook_dir }}"
      loop: "{{ host_files.files }}"
      loop_control:
        label: "{{ item.path | basename }}"
      register: macros_generation

    - name: Create Zabbix hosts groups
      community.zabbix.zabbix_group:
        state: present
        host_groups: "{{ item.path | basename | regex_replace('\\.(yaml|yml)$', '') | upper }}"
      loop: "{{ host_files.files }}"
      loop_control:
        label: "{{ item.path | basename }}"

    - name: Create Zabbix hosts from file names with macros
      community.zabbix.zabbix_host:
        host_name: "{{ item.path | basename | regex_replace('\\.(yaml|yml)$', '') | upper }}"
        host_groups:
          - "EIDA nodes"
          - "{{ item.path | basename | regex_replace('\\.(yaml|yml)$', '') | upper }}"
        link_templates:
          - "Template performance checks"
          - "Template webservices"
          - "Website certificate by Zabbix agent 2"
        status: "enabled"
        state: "present"
        interfaces:
          - type: 1
            useip: 1
            main: 1
            ip: "127.0.0.1"
            port: "10050"
        inventory_mode: "disabled"
        macros: "{{ lookup('file', macros_output_directory + '/' + item.path | basename) | from_yaml }}"
      loop: "{{ host_files.files }}"
      loop_control:
        label: "{{ item.path | basename }}"
      register: host_results

    - name: Display creation results
      ansible.builtin.debug:
        msg: >-
          Host '{{ item.item.path | basename | regex_replace('\.(yaml|yml)$', '') | upper }}':
          {{ 'Created/Updated' if item.changed else 'Already exists' }}
      loop: "{{ host_results.results }}"
      loop_control:
        label: "{{ item.item.path | basename }}"
