{
 "title": "EIDA global WeatherMap",
 "tags": [
  "EIDA",
  "public"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "15m",
 "panels": [
  {
   "title": "dataselect healthcheck",
   "type": "state-timeline",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "EIDA nodes" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "dataselect accessible" },
     "itemTag": { "filter": "dataselect: accessible" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "station healthcheck",
   "type": "state-timeline",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "EIDA nodes" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "station accessible" },
     "itemTag": { "filter": "station: accessible" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "availability healthcheck",
   "type": "state-timeline",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "EIDA nodes" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "availability accessible" },
     "itemTag": { "filter": "availability: accessible" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "wfcatalog healthcheck",
   "type": "state-timeline",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 51 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "EIDA nodes" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "wfcatalog accessible" },
     "itemTag": { "filter": "wfcatalog: accessible" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "seedpsd healthcheck",
   "type": "state-timeline",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 68 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "EIDA nodes" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "seedpsd accessible" },
     "itemTag": { "filter": "seedpsd: accessible" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  }
 ]
}