{
 "title": "EIDA Nodes requirements",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "EIDA_NODES",
    "label": "EIDA NODES",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "CORS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CORS availability",
   "type": "alexanderzobnin-zabbix-triggers-panel",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "application": { "filter": "" },
     "countTriggersBy": "problems",
     "evaltype": "0",
     "group": { "filter": "$EIDA_NODES" },
     "host": { "filter": "$EIDA_NODES" },
     "item": { "filter": "" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "acknowledged": 2,
      "count": true,
      "disableDataAlignment": false,
      "hostProxy": false,
      "hostsInMaintenance": false,
      "limit": 1001,
      "minSeverity": 0,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "sortProblems": "default",
      "useTimeRange": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "showProblems": "problems",
     "table": {
      "skipEmptyValues": false
     },
     "tags": {
      "filter": "Test:cors, Application:availability"
     },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "CORS dataselect",
   "type": "alexanderzobnin-zabbix-triggers-panel",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "application": { "filter": "" },
     "countTriggersBy": "problems",
     "evaltype": "0",
     "group": { "filter": "$EIDA_NODES" },
     "host": { "filter": "$EIDA_NODES" },
     "item": { "filter": "" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "acknowledged": 2,
      "count": true,
      "disableDataAlignment": false,
      "hostProxy": false,
      "hostsInMaintenance": false,
      "limit": 1001,
      "minSeverity": 0,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "sortProblems": "default",
      "useTimeRange": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "showProblems": "problems",
     "table": {
      "skipEmptyValues": false
     },
     "tags": {
      "filter": "Test:cors, Application:dataselect"
     },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "CORS station",
   "type": "alexanderzobnin-zabbix-triggers-panel",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "application": { "filter": "" },
     "countTriggersBy": "problems",
     "evaltype": "0",
     "group": { "filter": "$EIDA_NODES" },
     "host": { "filter": "$EIDA_NODES" },
     "item": { "filter": "" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "acknowledged": 2,
      "count": true,
      "disableDataAlignment": false,
      "hostProxy": false,
      "hostsInMaintenance": false,
      "limit": 1001,
      "minSeverity": 0,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "sortProblems": "default",
      "useTimeRange": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "showProblems": "problems",
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "Test:cors, Application:station" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "CORS wfcatalog",
   "type": "alexanderzobnin-zabbix-triggers-panel",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "application": { "filter": "" },
     "countTriggersBy": "problems",
     "evaltype": "0",
     "group": { "filter": "$EIDA_NODES" },
     "host": { "filter": "$EIDA_NODES" },
     "item": { "filter": "" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "acknowledged": 2,
      "count": true,
      "disableDataAlignment": false,
      "hostProxy": false,
      "hostsInMaintenance": false,
      "limit": 1001,
      "minSeverity": 0,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "sortProblems": "default",
      "useTimeRange": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "showProblems": "problems",
     "table": {
      "skipEmptyValues": false
     },
     "tags": {
      "filter": "Test:cors, Application:wfcatalog"
     },
     "trigger": { "filter": "" }
    }
   ]
  },
  { "title": "WADL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "dataselect WADL",
   "type": "state-timeline",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "$EIDA_NODES" },
     "host": { "filter": "$EIDA_NODES" },
     "item": {
      "filter": "Response code for step \"dataselect application.wadl\" of scenario \"dataselect\"."
     },
     "itemTag": { "filter": "Application: dataselect" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "station WADL",
   "type": "state-timeline",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 59 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "$EIDA_NODES" },
     "host": { "filter": "$EIDA_NODES" },
     "item": {
      "filter": "Response code for step \"application.wadl\" of scenario \"station\"."
     },
     "itemTag": { "filter": "Application: station" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "availability WADL",
   "type": "state-timeline",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 72 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "$EIDA_NODES" },
     "host": { "filter": "$EIDA_NODES" },
     "item": {
      "filter": "Response code for step \"availability application.wadl\" of scenario \"availability\"."
     },
     "itemTag": { "filter": "Application: availability" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "wfcatalog WADL",
   "type": "state-timeline",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 85 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "$EIDA_NODES" },
     "host": { "filter": "$EIDA_NODES" },
     "item": {
      "filter": "Response code for step \"wfcatalog application.wadl\" of scenario \"wfcatalog\"."
     },
     "itemTag": { "filter": "Application: wfcatalog" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  }
 ]
}