{
 "title": "EIDA services status timeline",
 "tags": [
  "EIDA",
  "public"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "dataselect healthcheck",
   "type": "state-timeline",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "EIDA nodes" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "dataselect healtcheck" },
     "itemTag": { "filter": "healtcheck" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": true,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "dataselect healthcheck v4",
   "type": "state-timeline",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "EIDA nodes" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "dataselect healtcheck v4" },
     "itemTag": { "filter": "healtcheck" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": true,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "station healthcheck",
   "type": "state-timeline",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "EIDA nodes" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "station healtcheck" },
     "itemTag": { "filter": "healtcheck" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": true,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "station healthcheck v4",
   "type": "state-timeline",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 51 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "EIDA nodes" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "station healtcheck v4" },
     "itemTag": { "filter": "healtcheck" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": true,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "availability healthcheck",
   "type": "state-timeline",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 68 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "EIDA nodes" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "availability healtcheck" },
     "itemTag": { "filter": "healtcheck" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": true,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "availability healthcheck_v4",
   "type": "state-timeline",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 85 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "EIDA nodes" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "availability healtcheck v4" },
     "itemTag": { "filter": "healtcheck" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": true,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "wfcatalog healthcheck",
   "type": "state-timeline",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 102 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "EIDA nodes" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "wfcatalog healtcheck" },
     "itemTag": { "filter": "healtcheck" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": true,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "wfcatalog healthcheck v4",
   "type": "state-timeline",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 119 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "EIDA nodes" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "wfcatalog healtcheck v4" },
     "itemTag": { "filter": "healtcheck" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": true,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "seedpsd healthcheck",
   "type": "state-timeline",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 136 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "EIDA nodes" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "seedpsd healtcheck" },
     "itemTag": { "filter": "healtcheck" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": true,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  }
 ]
}