config:
  SERVER_CRT: |
    -----BEGIN CERTIFICATE-----
    MIID2TCCAsGgAwIBAgIUQbYPyTpOLmKC0SDn3xTx7/mPyAcwDQYJKoZIhvcNAQEL
    BQAwgZQxCzAJBgNVBAYTAkZSMRMwEQYDVQQIDApTb21lLVN0YXRlMREwDwYDVQQH
    DAhHcmVub2JsZTEUMBIGA1UECgwLRXBvcy1GcmFuY2UxDTALBgNVBAsMBE9TVUcx
    FDASBgNVBAMMC3NwLnJlc2lmLmZyMSIwIAYJKoZIhvcNAQkBFhNzaXNtby1oZWxw
    QHJlc2lmLmZyMB4XDTI1MDIyMDE0MTIyMVoXDTQ1MDIxNTE0MTIyMVowgZQxCzAJ
    BgNVBAYTAkZSMRMwEQYDVQQIDApTb21lLVN0YXRlMREwDwYDVQQHDAhHcmVub2Js
    ZTEUMBIGA1UECgwLRXBvcy1GcmFuY2UxDTALBgNVBAsMBE9TVUcxFDASBgNVBAMM
    C3NwLnJlc2lmLmZyMSIwIAYJKoZIhvcNAQkBFhNzaXNtby1oZWxwQHJlc2lmLmZy
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjJ+01lh22/EQUKsHUcmz
    TJITDMnlbgq0BBGQTHlzuSpDXTaR06uvq8a4D4zxQbi0ij+9Cw9dML9B5IR7FcOF
    odxcRaxMTliv/uvPTFdq3gKkvz/DN/dIFCQnFa/KIeZivlsxCzCPCo6yllqLgmpH
    RoMFMBbbhdzvcn2Vav1Rn9eY49Nmy9ngxK3mW64+qOHrc+A1jZOmm2/NKYfjDCWh
    64dlttwXDAsK8BpMsAVnI6PRfCmAD8xEUwqZvN1DRh+Aw68Yhwii6SvkGY/2Hl7U
    WjP0MnBmz5+01Gp4b14Db3SBii4KQEOIoiW5ea2wZqCoO64InkaeTuB27snjW7hC
    ywIDAQABoyEwHzAdBgNVHQ4EFgQUM3vVw3eVqsVHqSySWuiiLMR/vcEwDQYJKoZI
    hvcNAQELBQADggEBABNFStsIsS/PpaX8uHrZVhAWsZ1uTHTHjAHqe20j6F61G2Fu
    Sf0XzvBVJedf9mdhXi1V+6uzg3n4LfCC5LnfS+xQu2mm90kjaZzx5LBVcEFla3+f
    I1vhE3VLjrbcBm47Xaz+f3CaKMdRTTZZpAjS23P3Oi+Qh/ZXCfBUKhvhTpNxDRXZ
    EgRE7blhogMQy9cuWJBFQVEz9eeh5vdykeDIPBBHGyHS2iHxB13zpM0rI9l3J4pY
    vLBRjby/tSTKG66NjVGaHDeS7kCWzizEBITD0+gieq6ULC/M8vztxQQfQtkPQgTQ
    ycz6bXZj0wsfgQ795w1ZDouXKrepA+wQEycAZZ0=
    -----END CERTIFICATE-----
