config:
    SERVER_CRT: |
        -----BEGIN CERTIFICATE-----
        MIID0TCCArmgAwIBAgIUDOMVGE+rkPD8/zMxrrHwJcFoPcMwDQYJKoZIhvcNAQEL
        BQAwgZAxCzAJBgNVBAYTAkZSMQ8wDQYDVQQIDAZGcmFuY2UxETAPBgNVBAcMCEdy
        ZW5vYmxlMRQwEgYDVQQKDAtFcG9zLUZyYW5jZTENMAsGA1UECwwET1NVRzEUMBIG
        A1UEAwwLc3AucmVzaWYuZnIxIjAgBgkqhkiG9w0BCQEWE3Npc21vLWhlbHBAcmVz
        aWYuZnIwHhcNMjUwMjIwMTQ1NDI0WhcNNDUwMjE1MTQ1NDI0WjCBkDELMAkGA1UE
        BhMCRlIxDzANBgNVBAgMBkZyYW5jZTERMA8GA1UEBwwIR3Jlbm9ibGUxFDASBgNV
        BAoMC0Vwb3MtRnJhbmNlMQ0wCwYDVQQLDARPU1VHMRQwEgYDVQQDDAtzcC5yZXNp
        Zi5mcjEiMCAGCSqGSIb3DQEJARYTc2lzbW8taGVscEByZXNpZi5mcjCCASIwDQYJ
        KoZIhvcNAQEBBQADggEPADCCAQoCggEBALcTRyPk1hr4ppbG3NAzUCD951/CD7RT
        j1hViHGuCl1isH0RvxhF3YOp8gbc/oOj2FkXW4gjqcei87V2otlGAwqTUcMjvCCS
        MPxuIs5vqou9XgWpSki1+a7UjuDIFlRRwpbikdFCHw6f9tCQXloQxcpSorwX2G57
        fMjYh4JKUGlezHx8/s3yDj76gr8FvzcQemcrt4/V2+oBeUdL51Pf6OwbRHqXUcuI
        NBcD+zn0i/oQiVmZgNK/kfuA5NUzbkpBZj6UbcLlrA5T1TjrIY/vlokD527Ui9Wy
        9ia+yY/Og2GthgijCwtdnE5akbQKP2+ennpWS8kdSyu6qlnpfJooXYkCAwEAAaMh
        MB8wHQYDVR0OBBYEFFC7xuW8QAJw9xlTk3FXk17d5xD7MA0GCSqGSIb3DQEBCwUA
        A4IBAQACX8qD1yQPbqN7pwhviqmWmdQDCTuRWkdEiknjH0CwIRC5EZ0xa999fYWY
        J1dSDsEQ62uq+Sfkai5b6RHxpJBb65dVVWM75Vsq67ymAm/w+L9Il3amFU841ZPf
        d2rs7rld9gqJWWNtWc2FczbNOTDC2LKWdAYf4rXPlT1kY0SFRO3vCJZrt3JSyIlL
        Kr/h2B89y5WH0/BQaQq8p9XBjpU8DlQCWHJqyLQQnP4GN7BR1l1bXNw/siIj4Ykr
        XQfO1NlsGofNdoGqX2XlOc+7ZvYNmuJhTXmGkR6Ia0zS+bNOLqf/dTLJ9Ia2fAKk
        dlJAD/p6xXV+vlsEevXO4QH4mcRg
        -----END CERTIFICATE-----
